const QUESTIONS = [
// ── L3: Fractions ────────────────────────────────────────
{id:'mf3_01',s:'maths',t:'Fractions',l:3,q:'What is ½ of 20?',o:['5','8','10','15'],a:'10',e:'Half means divide by 2. 20 ÷ 2 = 10'},
{id:'mf3_02',s:'maths',t:'Fractions',l:3,q:'What is ¼ of 16?',o:['2','4','6','8'],a:'4',e:'Quarter means divide by 4. 16 ÷ 4 = 4'},
{id:'mf3_03',s:'maths',t:'Fractions',l:3,q:'What is ¾ of 12?',o:['3','6','8','9'],a:'9',e:'¾ of 12: first find ¼ = 3, then × 3 = 9'},
{id:'mf3_04',s:'maths',t:'Fractions',l:3,q:'Which fraction is equivalent to ½?',o:['1/3','2/3','2/4','3/4'],a:'2/4',e:'2/4 = 1/2 because both numerator and denominator are doubled'},
{id:'mf3_05',s:'maths',t:'Fractions',l:3,q:'What is ⅓ of 15?',o:['3','4','5','6'],a:'5',e:'Third means divide by 3. 15 ÷ 3 = 5'},
{id:'mf3_06',s:'maths',t:'Fractions',l:3,q:'What is ⅔ of 12?',o:['4','6','8','10'],a:'8',e:'⅔ of 12: first ⅓ = 4, then × 2 = 8'},
{id:'mf3_07',s:'maths',t:'Fractions',l:3,q:'Which is larger: ½ or ⅓?',o:['½','⅓','They are equal','Cannot tell'],a:'½',e:'½ = 0.5, ⅓ ≈ 0.33. So ½ is larger.'},
{id:'mf3_08',s:'maths',t:'Fractions',l:3,q:'What is ¼ of 24?',o:['4','5','6','8'],a:'6',e:'24 ÷ 4 = 6'},
{id:'mf3_09',s:'maths',t:'Fractions',l:3,q:'What fraction of 10 is 5?',o:['1/5','1/4','1/3','1/2'],a:'1/2',e:'5 out of 10 = 5/10 = 1/2'},
{id:'mf3_10',s:'maths',t:'Fractions',l:3,q:'What is ¾ of 20?',o:['10','12','15','18'],a:'15',e:'¾ of 20: ¼ = 5, × 3 = 15'},
{id:'mf3_11',s:'maths',t:'Fractions',l:3,q:'½ as a percentage is…',o:['25%','50%','75%','100%'],a:'50%',e:'½ = 50 out of 100 = 50%'},
{id:'mf3_12',s:'maths',t:'Fractions',l:3,q:'What is ⅕ of 25?',o:['4','5','6','7'],a:'5',e:'25 ÷ 5 = 5'},
{id:'mf3_13',s:'maths',t:'Fractions',l:3,q:'Which fraction equals 2/4?',o:['1/3','1/2','2/3','3/4'],a:'1/2',e:'2/4 simplifies to 1/2 (divide both by 2)'},
{id:'mf3_14',s:'maths',t:'Fractions',l:3,q:'What is ⅖ of 20?',o:['4','6','8','10'],a:'8',e:'⅕ of 20 = 4, × 2 = 8'},
{id:'mf3_15',s:'maths',t:'Fractions',l:3,q:'What is 1/10 of 50?',o:['5','10','15','20'],a:'5',e:'50 ÷ 10 = 5'},
{id:'mf3_16',s:'maths',t:'Fractions',l:3,q:'Which is the smallest: ¼, ½ or ⅓?',o:['¼','½','⅓','They are equal'],a:'¼',e:'¼ = 0.25, ⅓ ≈ 0.33, ½ = 0.5. So ¼ is smallest.'},
{id:'mf3_17',s:'maths',t:'Fractions',l:3,q:'What is ⅗ of 10?',o:['3','5','6','8'],a:'6',e:'⅕ of 10 = 2, × 3 = 6'},
{id:'mf3_18',s:'maths',t:'Fractions',l:3,q:'What fraction of 20 is 10?',o:['¼','⅓','½','¾'],a:'½',e:'10/20 = 1/2'},
{id:'mf3_19',s:'maths',t:'Fractions',l:3,q:'½ + ¼ = ?',o:['2/6','½','¾','1'],a:'¾',e:'½ = 2/4, so 2/4 + 1/4 = 3/4'},
{id:'mf3_20',s:'maths',t:'Fractions',l:3,q:'What is ¼ of 100?',o:['10','20','25','40'],a:'25',e:'100 ÷ 4 = 25'},
// ── L4: Fractions ────────────────────────────────────────
{id:'mf4_01',s:'maths',t:'Fractions',l:4,q:'What is 3/8 + 1/4?',o:['4/12','1/2','5/8','7/8'],a:'5/8',e:'1/4 = 2/8, so 3/8 + 2/8 = 5/8'},
{id:'mf4_02',s:'maths',t:'Fractions',l:4,q:'What is 5/6 − 1/3?',o:['4/3','4/6','1/2','2/3'],a:'1/2',e:'1/3 = 2/6, so 5/6 − 2/6 = 3/6 = 1/2'},
{id:'mf4_03',s:'maths',t:'Fractions',l:4,q:'Simplify 18/24.',o:['3/4','6/8','9/12','2/3'],a:'3/4',e:'18/24: divide both by 6 → 3/4'},
{id:'mf4_04',s:'maths',t:'Fractions',l:4,q:'Convert 11/4 to a mixed number.',o:['2¼','2¾','3¼','1¾'],a:'2¾',e:'11 ÷ 4 = 2 remainder 3, so 2¾'},
{id:'mf4_05',s:'maths',t:'Fractions',l:4,q:'What is 2/3 × 9?',o:['3','6','9','18'],a:'6',e:'2/3 × 9 = (2 × 9) ÷ 3 = 18 ÷ 3 = 6'},
{id:'mf4_06',s:'maths',t:'Fractions',l:4,q:'Which is greatest: 3/4, 7/10, or 5/8?',o:['3/4','7/10','5/8','They are equal'],a:'3/4',e:'3/4=0.75, 7/10=0.70, 5/8=0.625. So 3/4 is greatest.'},
{id:'mf4_07',s:'maths',t:'Fractions',l:4,q:'What is 4/5 of 35?',o:['20','24','28','32'],a:'28',e:'1/5 of 35 = 7, × 4 = 28'},
{id:'mf4_08',s:'maths',t:'Fractions',l:4,q:'What is 1¾ + 2½?',o:['3¼','4','4¼','4½'],a:'4¼',e:'1¾ + 2½ = 1 3/4 + 2 2/4 = 3 5/4 = 4 1/4'},
{id:'mf4_09',s:'maths',t:'Fractions',l:4,q:'Convert 3⅖ to an improper fraction.',o:['15/5','17/5','16/5','18/5'],a:'17/5',e:'3 × 5 = 15, + 2 = 17 → 17/5'},
{id:'mf4_10',s:'maths',t:'Fractions',l:4,q:'3/4 − 1/6 = ?',o:['2/3','7/12','1/2','5/12'],a:'7/12',e:'Common denominator 12: 9/12 − 2/12 = 7/12'},
{id:'mf4_11',s:'maths',t:'Fractions',l:4,q:'What is 5/6 of 24?',o:['15','18','20','22'],a:'20',e:'1/6 of 24 = 4, × 5 = 20'},
{id:'mf4_12',s:'maths',t:'Fractions',l:4,q:'Simplify 36/48.',o:['3/4','2/3','6/8','9/12'],a:'3/4',e:'36/48: divide both by 12 → 3/4'},
{id:'mf4_13',s:'maths',t:'Fractions',l:4,q:'What is 7/10 + 1/4?',o:['8/14','9/20','19/20','4/5'],a:'19/20',e:'Common denominator 20: 14/20 + 5/20 = 19/20'},
{id:'mf4_14',s:'maths',t:'Fractions',l:4,q:'2/3 + 3/4 = ?',o:['5/7','5/12','17/12','1½'],a:'17/12',e:'Common denominator 12: 8/12 + 9/12 = 17/12'},
{id:'mf4_15',s:'maths',t:'Fractions',l:4,q:'What is 3/5 ÷ 3?',o:['9/5','1/5','3/15','1/3'],a:'1/5',e:'Dividing a fraction by 3: 3/5 ÷ 3 = 3/15 = 1/5'},
{id:'mf4_16',s:'maths',t:'Fractions',l:4,q:'A recipe needs 2/3 cup sugar for 8 biscuits. How much for 24 biscuits?',o:['1 cup','1½ cups','2 cups','2½ cups'],a:'2 cups',e:'24 is 3× more than 8, so 2/3 × 3 = 2 cups'},
{id:'mf4_17',s:'maths',t:'Fractions',l:4,q:'What is 1⅔ × 6?',o:['7','8','10','12'],a:'10',e:'1⅔ = 5/3. 5/3 × 6 = 30/3 = 10'},
{id:'mf4_18',s:'maths',t:'Fractions',l:4,q:'Which fraction is between 1/2 and 3/4?',o:['1/3','2/5','5/8','7/8'],a:'5/8',e:'5/8 = 0.625, which is between 0.5 and 0.75'},
{id:'mf4_19',s:'maths',t:'Fractions',l:4,q:'What is 5/8 as a decimal?',o:['0.58','0.625','0.65','0.8'],a:'0.625',e:'5 ÷ 8 = 0.625'},
{id:'mf4_20',s:'maths',t:'Fractions',l:4,q:'Jake ate 3/8 of a pizza. Mia ate 1/4. What fraction is left?',o:['3/8','4/8','3/4','5/8'],a:'3/8',e:'3/8 + 2/8 = 5/8 eaten. 8/8 − 5/8 = 3/8 left'},
// ── L3: Multiplication & Division ────────────────────────
{id:'mmd3_01',s:'maths',t:'Multiplication & Division',l:3,q:'6 × 7 = ?',o:['36','42','48','54'],a:'42',e:'6 × 7 = 42'},
{id:'mmd3_02',s:'maths',t:'Multiplication & Division',l:3,q:'8 × 9 = ?',o:['63','64','72','81'],a:'72',e:'8 × 9 = 72'},
{id:'mmd3_03',s:'maths',t:'Multiplication & Division',l:3,q:'48 ÷ 6 = ?',o:['6','7','8','9'],a:'8',e:'48 ÷ 6 = 8'},
{id:'mmd3_04',s:'maths',t:'Multiplication & Division',l:3,q:'7 × 8 = ?',o:['48','54','56','63'],a:'56',e:'7 × 8 = 56'},
{id:'mmd3_05',s:'maths',t:'Multiplication & Division',l:3,q:'63 ÷ 7 = ?',o:['7','8','9','10'],a:'9',e:'63 ÷ 7 = 9'},
{id:'mmd3_06',s:'maths',t:'Multiplication & Division',l:3,q:'9 × 6 = ?',o:['45','48','54','56'],a:'54',e:'9 × 6 = 54'},
{id:'mmd3_07',s:'maths',t:'Multiplication & Division',l:3,q:'56 ÷ 8 = ?',o:['5','6','7','8'],a:'7',e:'56 ÷ 8 = 7'},
{id:'mmd3_08',s:'maths',t:'Multiplication & Division',l:3,q:'12 × 7 = ?',o:['74','80','84','96'],a:'84',e:'12 × 7 = 84'},
{id:'mmd3_09',s:'maths',t:'Multiplication & Division',l:3,q:'72 ÷ 9 = ?',o:['6','7','8','9'],a:'8',e:'72 ÷ 9 = 8'},
{id:'mmd3_10',s:'maths',t:'Multiplication & Division',l:3,q:'11 × 8 = ?',o:['80','84','88','96'],a:'88',e:'11 × 8 = 88'},
{id:'mmd3_11',s:'maths',t:'Multiplication & Division',l:3,q:'144 ÷ 12 = ?',o:['10','11','12','13'],a:'12',e:'144 ÷ 12 = 12'},
{id:'mmd3_12',s:'maths',t:'Multiplication & Division',l:3,q:'9 × 9 = ?',o:['72','81','90','99'],a:'81',e:'9 × 9 = 81'},
{id:'mmd3_13',s:'maths',t:'Multiplication & Division',l:3,q:'A baker makes 9 cakes per day. How many in 6 days?',o:['45','54','56','63'],a:'54',e:'9 × 6 = 54'},
{id:'mmd3_14',s:'maths',t:'Multiplication & Division',l:3,q:'6 × 12 = ?',o:['62','70','72','84'],a:'72',e:'6 × 12 = 72'},
{id:'mmd3_15',s:'maths',t:'Multiplication & Division',l:3,q:'96 ÷ 8 = ?',o:['10','11','12','13'],a:'12',e:'96 ÷ 8 = 12 because 8 × 12 = 96'},
{id:'mmd3_16',s:'maths',t:'Multiplication & Division',l:3,q:'7 rows of 9 chairs — how many total?',o:['54','56','62','63'],a:'63',e:'7 × 9 = 63'},
{id:'mmd3_17',s:'maths',t:'Multiplication & Division',l:3,q:'7 × 11 = ?',o:['70','74','77','84'],a:'77',e:'7 × 11 = 77'},
{id:'mmd3_18',s:'maths',t:'Multiplication & Division',l:3,q:'84 ÷ 7 = ?',o:['10','11','12','14'],a:'12',e:'84 ÷ 7 = 12'},
{id:'mmd3_19',s:'maths',t:'Multiplication & Division',l:3,q:'108 ÷ 9 = ?',o:['10','11','12','13'],a:'12',e:'108 ÷ 9 = 12'},
{id:'mmd3_20',s:'maths',t:'Multiplication & Division',l:3,q:'8 × 12 = ?',o:['88','92','96','104'],a:'96',e:'8 × 12 = 96'},
// ── L4: Multiplication & Division ────────────────────────
{id:'mmd4_01',s:'maths',t:'Multiplication & Division',l:4,q:'24 × 15 = ?',o:['300','340','360','380'],a:'360',e:'24 × 15 = 24 × 10 + 24 × 5 = 240 + 120 = 360'},
{id:'mmd4_02',s:'maths',t:'Multiplication & Division',l:4,q:'342 ÷ 6 = ?',o:['54','57','58','62'],a:'57',e:'342 ÷ 6: 6 × 57 = 342'},
{id:'mmd4_03',s:'maths',t:'Multiplication & Division',l:4,q:'What is the remainder when 125 ÷ 8?',o:['3','4','5','6'],a:'5',e:'8 × 15 = 120, 125 − 120 = 5 remainder'},
{id:'mmd4_04',s:'maths',t:'Multiplication & Division',l:4,q:'37 × 12 = ?',o:['404','434','444','454'],a:'444',e:'37 × 12 = 37 × 10 + 37 × 2 = 370 + 74 = 444'},
{id:'mmd4_05',s:'maths',t:'Multiplication & Division',l:4,q:'256 ÷ 16 = ?',o:['14','15','16','17'],a:'16',e:'16 × 16 = 256'},
{id:'mmd4_06',s:'maths',t:'Multiplication & Division',l:4,q:'How many factors does 36 have?',o:['7','8','9','10'],a:'9',e:'Factors of 36: 1,2,3,4,6,9,12,18,36 — that\'s 9 factors'},
{id:'mmd4_07',s:'maths',t:'Multiplication & Division',l:4,q:'What is the LCM of 4 and 6?',o:['8','10','12','24'],a:'12',e:'Multiples of 4: 4,8,12… Multiples of 6: 6,12… LCM = 12'},
{id:'mmd4_08',s:'maths',t:'Multiplication & Division',l:4,q:'504 ÷ 7 = ?',o:['62','70','72','74'],a:'72',e:'7 × 72 = 504'},
{id:'mmd4_09',s:'maths',t:'Multiplication & Division',l:4,q:'3.5 × 6 = ?',o:['18','20','21','24'],a:'21',e:'3.5 × 6 = 3 × 6 + 0.5 × 6 = 18 + 3 = 21'},
{id:'mmd4_10',s:'maths',t:'Multiplication & Division',l:4,q:'625 ÷ 25 = ?',o:['20','23','25','30'],a:'25',e:'25 × 25 = 625'},
{id:'mmd4_11',s:'maths',t:'Multiplication & Division',l:4,q:'48 × 25 = ?',o:['1,000','1,100','1,200','1,400'],a:'1,200',e:'48 × 25 = 48 × 100 ÷ 4 = 4800 ÷ 4 = 1,200'},
{id:'mmd4_12',s:'maths',t:'Multiplication & Division',l:4,q:'What is 5² × 4?',o:['40','80','100','120'],a:'100',e:'5² = 25, 25 × 4 = 100'},
{id:'mmd4_13',s:'maths',t:'Multiplication & Division',l:4,q:'432 ÷ 9 = ?',o:['44','46','48','52'],a:'48',e:'9 × 48 = 432'},
{id:'mmd4_14',s:'maths',t:'Multiplication & Division',l:4,q:'How many 15s in 225?',o:['13','14','15','16'],a:'15',e:'225 ÷ 15 = 15 (15 × 15 = 225)'},
{id:'mmd4_15',s:'maths',t:'Multiplication & Division',l:4,q:'28 × 35 = ?',o:['840','900','960','980'],a:'980',e:'28 × 35 = 28 × 30 + 28 × 5 = 840 + 140 = 980'},
{id:'mmd4_16',s:'maths',t:'Multiplication & Division',l:4,q:'84 ÷ 3 + 6 × 4 = ?',o:['40','48','52','56'],a:'52',e:'BODMAS: 84 ÷ 3 = 28, 6 × 4 = 24, 28 + 24 = 52'},
{id:'mmd4_17',s:'maths',t:'Multiplication & Division',l:4,q:'4 × 13 × 5 = ?',o:['200','240','260','280'],a:'260',e:'4 × 5 = 20, 20 × 13 = 260'},
{id:'mmd4_18',s:'maths',t:'Multiplication & Division',l:4,q:'What is the HCF of 24 and 36?',o:['4','6','8','12'],a:'12',e:'Factors of 24: 1,2,3,4,6,8,12,24. Factors of 36: 1,2,3,4,6,9,12,18,36. HCF = 12'},
{id:'mmd4_19',s:'maths',t:'Multiplication & Division',l:4,q:'576 ÷ 24 = ?',o:['22','24','26','28'],a:'24',e:'24 × 24 = 576'},
{id:'mmd4_20',s:'maths',t:'Multiplication & Division',l:4,q:'A box holds 18 oranges. How many boxes for 270 oranges?',o:['13','14','15','16'],a:'15',e:'270 ÷ 18 = 15'},
// ── L3: Place Value & Number ──────────────────────────────
{id:'mpv3_01',s:'maths',t:'Place Value & Number',l:3,q:'What is the value of the digit 7 in 473?',o:['7','70','700','7000'],a:'70',e:'In 473, the 7 is in the tens column = 70'},
{id:'mpv3_02',s:'maths',t:'Place Value & Number',l:3,q:'What is 346 rounded to the nearest 10?',o:['300','340','350','400'],a:'350',e:'346: the units digit is 6 (≥5), so round up to 350'},
{id:'mpv3_03',s:'maths',t:'Place Value & Number',l:3,q:'Which is the largest: 526, 562, 256, 625?',o:['526','562','256','625'],a:'625',e:'Comparing hundreds: 6 > 5 > 2, so 625 is largest'},
{id:'mpv3_04',s:'maths',t:'Place Value & Number',l:3,q:'What is 580 rounded to the nearest 100?',o:['500','550','600','700'],a:'600',e:'580: tens digit is 8 (≥5), round up to 600'},
{id:'mpv3_05',s:'maths',t:'Place Value & Number',l:3,q:'What number is 100 more than 750?',o:['760','800','850','950'],a:'850',e:'750 + 100 = 850'},
{id:'mpv3_06',s:'maths',t:'Place Value & Number',l:3,q:'Write seven hundred and sixty-three in digits.',o:['367','637','673','763'],a:'763',e:'Seven hundred = 700, sixty = 60, three = 3 → 763'},
{id:'mpv3_07',s:'maths',t:'Place Value & Number',l:3,q:'What is the value of the 5 in 2,504?',o:['5','50','500','5000'],a:'500',e:'In 2,504 the digit 5 is in the hundreds column = 500'},
{id:'mpv3_08',s:'maths',t:'Place Value & Number',l:3,q:'Order smallest first: 842, 248, 428, 824',o:['248,428,824,842','248,428,842,824','428,248,824,842','248,824,428,842'],a:'248,428,824,842',e:'Compare hundreds: 2<4<8, then 824<842'},
{id:'mpv3_09',s:'maths',t:'Place Value & Number',l:3,q:'What is -3 + 5?',o:['-8','-2','2','8'],a:'2',e:'Start at -3, move 5 right = 2'},
{id:'mpv3_10',s:'maths',t:'Place Value & Number',l:3,q:'Which temperature is colder: -4°C or -7°C?',o:['-4°C','-7°C','They are equal','Cannot tell'],a:'-7°C',e:'On a number line, -7 is further left (colder) than -4'},
{id:'mpv3_11',s:'maths',t:'Place Value & Number',l:3,q:'What is 1,000 less than 4,567?',o:['3,456','3,567','4,467','4,557'],a:'3,567',e:'4,567 − 1,000 = 3,567'},
{id:'mpv3_12',s:'maths',t:'Place Value & Number',l:3,q:'Round 3,748 to the nearest 100.',o:['3,600','3,700','3,800','4,000'],a:'3,700',e:'3,748: tens digit is 4 (< 5), round down to 3,700'},
{id:'mpv3_13',s:'maths',t:'Place Value & Number',l:3,q:'How many tens are there in 350?',o:['3','5','35','350'],a:'35',e:'350 ÷ 10 = 35 tens'},
{id:'mpv3_14',s:'maths',t:'Place Value & Number',l:3,q:'What is 10 × 10?',o:['20','100','1,000','10,000'],a:'100',e:'10 × 10 = 100'},
{id:'mpv3_15',s:'maths',t:'Place Value & Number',l:3,q:'Which of these is an even number?',o:['137','249','362','475'],a:'362',e:'Even numbers end in 0,2,4,6,8. Only 362 ends in 2.'},
// ── L4: Place Value & Number ──────────────────────────────
{id:'mpv4_01',s:'maths',t:'Place Value & Number',l:4,q:'What is 3.45 rounded to 1 decimal place?',o:['3.4','3.5','3.6','4.0'],a:'3.5',e:'3.45 — the hundredths digit is 5, so round up: 3.5'},
{id:'mpv4_02',s:'maths',t:'Place Value & Number',l:4,q:'What is the value of the digit 7 in 3.718?',o:['7','7 tenths','7 hundredths','7 thousandths'],a:'7 tenths',e:'In 3.718, the 7 is in the tenths column = 7 tenths'},
{id:'mpv4_03',s:'maths',t:'Place Value & Number',l:4,q:'What is 5.2 × 100?',o:['52','520','5,200','0.052'],a:'520',e:'Multiply by 100: move decimal 2 places right → 520'},
{id:'mpv4_04',s:'maths',t:'Place Value & Number',l:4,q:'Which is smallest: 4.09, 4.9, 4.19, 4.019?',o:['4.09','4.9','4.19','4.019'],a:'4.019',e:'4.019 < 4.09 < 4.19 < 4.9'},
{id:'mpv4_05',s:'maths',t:'Place Value & Number',l:4,q:'What is 10³?',o:['30','300','1,000','10,000'],a:'1,000',e:'10³ = 10 × 10 × 10 = 1,000'},
{id:'mpv4_06',s:'maths',t:'Place Value & Number',l:4,q:'What is 7.5 ÷ 100?',o:['0.075','0.75','75','750'],a:'0.075',e:'Divide by 100: move decimal 2 places left → 0.075'},
{id:'mpv4_07',s:'maths',t:'Place Value & Number',l:4,q:'What is 1,000 more than 47,832?',o:['47,932','48,732','48,832','57,832'],a:'48,832',e:'47,832 + 1,000 = 48,832'},
{id:'mpv4_08',s:'maths',t:'Place Value & Number',l:4,q:'What digit is in the thousandths place in 5.2637?',o:['2','6','3','7'],a:'3',e:'5.2637 — tenths:2, hundredths:6, thousandths:3'},
{id:'mpv4_09',s:'maths',t:'Place Value & Number',l:4,q:'Which is smaller: 0.302 or 0.32?',o:['0.302','0.32','They are equal','Cannot tell'],a:'0.302',e:'0.302 = 0.302, 0.32 = 0.320. So 0.302 < 0.320'},
{id:'mpv4_10',s:'maths',t:'Place Value & Number',l:4,q:'Round 4.847 to 2 decimal places.',o:['4.84','4.85','4.9','5.0'],a:'4.85',e:'4.847 — third decimal is 7 (≥5), round up: 4.85'},
{id:'mpv4_11',s:'maths',t:'Place Value & Number',l:4,q:'What is the value of 6 in 562,841?',o:['6,000','60,000','600,000','6,000,000'],a:'60,000',e:'In 562,841: the 6 is in the ten-thousands column = 60,000'},
{id:'mpv4_12',s:'maths',t:'Place Value & Number',l:4,q:'0.5 + 0.25 + 0.125 = ?',o:['0.750','0.825','0.875','0.900'],a:'0.875',e:'0.500 + 0.250 + 0.125 = 0.875'},
{id:'mpv4_13',s:'maths',t:'Place Value & Number',l:4,q:'What comes next: 2.5, 3.0, 3.5, ___?',o:['3.8','4.0','4.5','5.0'],a:'4.0',e:'The sequence adds 0.5 each time. 3.5 + 0.5 = 4.0'},
{id:'mpv4_14',s:'maths',t:'Place Value & Number',l:4,q:'Which is greatest: 4.099, 4.1, 4.09, 4.0999?',o:['4.099','4.1','4.09','4.0999'],a:'4.1',e:'4.1 = 4.1000, which is largest of all four'},
{id:'mpv4_15',s:'maths',t:'Place Value & Number',l:4,q:'What is 9.25 − 3.8?',o:['5.35','5.45','6.15','6.45'],a:'5.45',e:'9.25 − 3.80 = 5.45'},
{id:'mpv4_16',s:'maths',t:'Place Value & Number',l:4,q:'Write 40,000 + 3,000 + 70 + 8 as a single number.',o:['4,378','43,078','43,780','430,078'],a:'43,078',e:'40,000 + 3,000 = 43,000 + 70 = 43,070 + 8 = 43,078'},
{id:'mpv4_17',s:'maths',t:'Place Value & Number',l:4,q:'What is 0.08 × 10?',o:['0.008','0.08','0.8','8'],a:'0.8',e:'0.08 × 10: move decimal one place right → 0.8'},
{id:'mpv4_18',s:'maths',t:'Place Value & Number',l:4,q:'Round 67,455 to the nearest 1,000.',o:['67,000','67,400','67,500','68,000'],a:'67,000',e:'67,455: hundreds digit is 4 (< 5), round down → 67,000'},
{id:'mpv4_19',s:'maths',t:'Place Value & Number',l:4,q:'What is the product of 0.4 × 0.3?',o:['0.07','0.12','1.2','12'],a:'0.12',e:'4 × 3 = 12; both have 1 decimal place each → 0.12'},
{id:'mpv4_20',s:'maths',t:'Place Value & Number',l:4,q:'A number has 4 in the millions place. What is the smallest it could be?',o:['400,000','4,000,000','4,000,001','4,999,999'],a:'4,000,000',e:'The smallest number with 4 in the millions column is 4,000,000'},
// ── L3: Addition & Subtraction ────────────────────────────
{id:'mas3_01',s:'maths',t:'Addition & Subtraction',l:3,q:'345 + 267 = ?',o:['502','602','612','622'],a:'612',e:'345 + 267 = 612'},
{id:'mas3_02',s:'maths',t:'Addition & Subtraction',l:3,q:'500 − 237 = ?',o:['263','273','283','363'],a:'263',e:'500 − 237 = 263'},
{id:'mas3_03',s:'maths',t:'Addition & Subtraction',l:3,q:'628 + 145 = ?',o:['763','773','783','793'],a:'773',e:'628 + 145 = 773'},
{id:'mas3_04',s:'maths',t:'Addition & Subtraction',l:3,q:'A shop has 432 apples. 178 are sold. How many left?',o:['244','254','264','274'],a:'254',e:'432 − 178 = 254'},
{id:'mas3_05',s:'maths',t:'Addition & Subtraction',l:3,q:'867 − 349 = ?',o:['418','508','518','528'],a:'518',e:'867 − 349 = 518'},
{id:'mas3_06',s:'maths',t:'Addition & Subtraction',l:3,q:'What is 999 + 1?',o:['1,000','1,009','1,099','1,999'],a:'1,000',e:'999 + 1 = 1,000'},
{id:'mas3_07',s:'maths',t:'Addition & Subtraction',l:3,q:'274 + 358 = ?',o:['522','622','632','642'],a:'632',e:'274 + 358 = 632'},
{id:'mas3_08',s:'maths',t:'Addition & Subtraction',l:3,q:'700 − 456 = ?',o:['234','244','254','264'],a:'244',e:'700 − 456 = 244'},
{id:'mas3_09',s:'maths',t:'Addition & Subtraction',l:3,q:'453 + 229 = ?',o:['672','682','692','782'],a:'682',e:'453 + 229 = 682'},
{id:'mas3_10',s:'maths',t:'Addition & Subtraction',l:3,q:'1,000 − 375 = ?',o:['525','625','635','725'],a:'625',e:'1,000 − 375 = 625'},
// ── L3: Decimals ──────────────────────────────────────────
{id:'mdc3_01',s:'maths',t:'Decimals',l:3,q:'What is 0.5 + 0.5?',o:['0.1','0.55','1.0','5.5'],a:'1.0',e:'0.5 + 0.5 = 1.0'},
{id:'mdc3_02',s:'maths',t:'Decimals',l:3,q:'Which is larger: 0.7 or 0.3?',o:['0.7','0.3','They are equal','Cannot tell'],a:'0.7',e:'7 tenths > 3 tenths'},
{id:'mdc3_03',s:'maths',t:'Decimals',l:3,q:'What is 1.5 + 2.5?',o:['3.0','3.5','4.0','4.5'],a:'4.0',e:'1.5 + 2.5 = 4.0'},
{id:'mdc3_04',s:'maths',t:'Decimals',l:3,q:'Write 0.25 as a fraction.',o:['1/2','1/4','1/5','1/8'],a:'1/4',e:'0.25 = 25/100 = 1/4'},
{id:'mdc3_05',s:'maths',t:'Decimals',l:3,q:'Order smallest first: 0.6, 0.1, 0.4',o:['0.6,0.4,0.1','0.1,0.4,0.6','0.4,0.1,0.6','0.1,0.6,0.4'],a:'0.1,0.4,0.6',e:'0.1 < 0.4 < 0.6'},
{id:'mdc3_06',s:'maths',t:'Decimals',l:3,q:'What is 2.4 + 1.6?',o:['3.0','3.8','4.0','4.2'],a:'4.0',e:'2.4 + 1.6 = 4.0'},
{id:'mdc3_07',s:'maths',t:'Decimals',l:3,q:'What is 0.1 as a percentage?',o:['1%','10%','100%','0.1%'],a:'10%',e:'0.1 = 1/10 = 10%'},
{id:'mdc3_08',s:'maths',t:'Decimals',l:3,q:'A pencil is 15.5 cm. Round to the nearest cm.',o:['15 cm','16 cm','15.5 cm','20 cm'],a:'16 cm',e:'15.5 → round up to 16 cm'},
// ── L3: Percentages ───────────────────────────────────────
{id:'mpc3_01',s:'maths',t:'Percentages',l:3,q:'What is 50% of 80?',o:['20','30','40','50'],a:'40',e:'50% = half. 80 ÷ 2 = 40'},
{id:'mpc3_02',s:'maths',t:'Percentages',l:3,q:'What is 25% of 40?',o:['5','8','10','15'],a:'10',e:'25% = quarter. 40 ÷ 4 = 10'},
{id:'mpc3_03',s:'maths',t:'Percentages',l:3,q:'What is 10% of 70?',o:['7','17','70','700'],a:'7',e:'10%: divide by 10. 70 ÷ 10 = 7'},
{id:'mpc3_04',s:'maths',t:'Percentages',l:3,q:'What is 100% of 55?',o:['5','50','55','100'],a:'55',e:'100% of any number = the number itself'},
{id:'mpc3_05',s:'maths',t:'Percentages',l:3,q:'30 pupils, 60% are girls. How many girls?',o:['6','12','18','20'],a:'18',e:'10% of 30 = 3, × 6 = 18'},
{id:'mpc3_06',s:'maths',t:'Percentages',l:3,q:'What is 10% of 250?',o:['2.5','25','250','2,500'],a:'25',e:'250 ÷ 10 = 25'},
{id:'mpc3_07',s:'maths',t:'Percentages',l:3,q:'What is 50% of 130?',o:['13','50','65','130'],a:'65',e:'130 ÷ 2 = 65'},
{id:'mpc3_08',s:'maths',t:'Percentages',l:3,q:'What percentage is 3 out of 10?',o:['3%','10%','30%','33%'],a:'30%',e:'3/10 = 30/100 = 30%'},
// ── L3: Geometry – Shapes ─────────────────────────────────
{id:'mgs3_01',s:'maths',t:'Geometry – Shapes',l:3,q:'How many sides does a hexagon have?',o:['4','5','6','7'],a:'6',e:'Hexagon = 6 sides'},
{id:'mgs3_02',s:'maths',t:'Geometry – Shapes',l:3,q:'What is the name of a 3-sided shape?',o:['Square','Rectangle','Triangle','Pentagon'],a:'Triangle',e:'Triangle = 3 sides'},
{id:'mgs3_03',s:'maths',t:'Geometry – Shapes',l:3,q:'How many faces does a cube have?',o:['4','5','6','8'],a:'6',e:'A cube has 6 square faces'},
{id:'mgs3_04',s:'maths',t:'Geometry – Shapes',l:3,q:'What is a quadrilateral?',o:['3-sided','4-sided','5-sided','6-sided'],a:'4-sided',e:'Quadrilateral = 4 sides'},
{id:'mgs3_05',s:'maths',t:'Geometry – Shapes',l:3,q:'How many lines of symmetry does a square have?',o:['1','2','3','4'],a:'4',e:'A square has 4 lines of symmetry'},
{id:'mgs3_06',s:'maths',t:'Geometry – Shapes',l:3,q:'How many vertices does a cuboid have?',o:['4','6','8','12'],a:'8',e:'A cuboid has 8 vertices'},
{id:'mgs3_07',s:'maths',t:'Geometry – Shapes',l:3,q:'5 faces, 5 vertices, 8 edges — which shape?',o:['Cube','Triangular prism','Square-based pyramid','Cylinder'],a:'Square-based pyramid',e:'Square-based pyramid: 1 square + 4 triangular faces'},
{id:'mgs3_08',s:'maths',t:'Geometry – Shapes',l:3,q:'An equilateral triangle has…',o:['All sides different','2 equal sides','All sides equal','No equal sides'],a:'All sides equal',e:'Equilateral = all sides and angles equal'},
// ── L3: Angles ────────────────────────────────────────────
{id:'mang3_01',s:'maths',t:'Angles',l:3,q:'How many degrees in a right angle?',o:['45°','90°','180°','360°'],a:'90°',e:'A right angle = 90°'},
{id:'mang3_02',s:'maths',t:'Angles',l:3,q:'An angle less than 90° is called…',o:['Acute','Right','Obtuse','Reflex'],a:'Acute',e:'Acute angles are less than 90°'},
{id:'mang3_03',s:'maths',t:'Angles',l:3,q:'An angle between 90° and 180° is called…',o:['Acute','Right','Obtuse','Straight'],a:'Obtuse',e:'Obtuse angles are between 90° and 180°'},
{id:'mang3_04',s:'maths',t:'Angles',l:3,q:'Angles in a triangle add up to…',o:['90°','180°','270°','360°'],a:'180°',e:'All three angles in any triangle sum to 180°'},
{id:'mang3_05',s:'maths',t:'Angles',l:3,q:'Angles on a straight line add up to…',o:['90°','180°','270°','360°'],a:'180°',e:'Angles on a straight line = 180°'},
{id:'mang3_06',s:'maths',t:'Angles',l:3,q:'A triangle has angles 60° and 80°. What is the third?',o:['30°','40°','50°','60°'],a:'40°',e:'180 − 60 − 80 = 40°'},
{id:'mang3_07',s:'maths',t:'Angles',l:3,q:'How many degrees in a full turn?',o:['90°','180°','270°','360°'],a:'360°',e:'A full rotation = 360°'},
{id:'mang3_08',s:'maths',t:'Angles',l:3,q:'One angle on a straight line is 110°. What is the other?',o:['60°','70°','80°','90°'],a:'70°',e:'180 − 110 = 70°'},
// ── L3: Measurement & Units ───────────────────────────────
{id:'mmu3_01',s:'maths',t:'Measurement & Units',l:3,q:'How many centimetres in 1 metre?',o:['10','100','1,000','10,000'],a:'100',e:'1 m = 100 cm'},
{id:'mmu3_02',s:'maths',t:'Measurement & Units',l:3,q:'How many grams in 1 kilogram?',o:['10','100','1,000','10,000'],a:'1,000',e:'1 kg = 1,000 g'},
{id:'mmu3_03',s:'maths',t:'Measurement & Units',l:3,q:'How many millilitres in 1 litre?',o:['10','100','1,000','10,000'],a:'1,000',e:'1 litre = 1,000 ml'},
{id:'mmu3_04',s:'maths',t:'Measurement & Units',l:3,q:'Convert 2.5 kg to grams.',o:['25 g','250 g','2,500 g','25,000 g'],a:'2,500 g',e:'2.5 × 1,000 = 2,500 g'},
{id:'mmu3_05',s:'maths',t:'Measurement & Units',l:3,q:'Film starts 3:15 pm, lasts 90 min. When does it end?',o:['4:00 pm','4:30 pm','4:45 pm','5:00 pm'],a:'4:45 pm',e:'3:15 + 45 min = 4:00, + 45 more = 4:45 pm'},
{id:'mmu3_06',s:'maths',t:'Measurement & Units',l:3,q:'How many minutes in 2 hours?',o:['60','90','100','120'],a:'120',e:'2 × 60 = 120 minutes'},
{id:'mmu3_07',s:'maths',t:'Measurement & Units',l:3,q:'Convert 350 cm to metres.',o:['0.35 m','3.5 m','35 m','3,500 m'],a:'3.5 m',e:'350 ÷ 100 = 3.5 m'},
{id:'mmu3_08',s:'maths',t:'Measurement & Units',l:3,q:'Which is heavier: 1.5 kg or 1,450 g?',o:['1.5 kg','1,450 g','They are equal','Cannot tell'],a:'1.5 kg',e:'1.5 kg = 1,500 g > 1,450 g'},
// ── L3: Perimeter & Area ──────────────────────────────────
{id:'mpa3_01',s:'maths',t:'Perimeter & Area',l:3,q:'Perimeter of a rectangle 6 cm × 4 cm?',o:['10 cm','20 cm','24 cm','48 cm'],a:'20 cm',e:'Perimeter = 2(6+4) = 20 cm'},
{id:'mpa3_02',s:'maths',t:'Perimeter & Area',l:3,q:'Area of a rectangle 5 cm × 3 cm?',o:['8 cm²','15 cm²','16 cm²','30 cm²'],a:'15 cm²',e:'Area = 5 × 3 = 15 cm²'},
{id:'mpa3_03',s:'maths',t:'Perimeter & Area',l:3,q:'A square has 7 cm sides. What is its perimeter?',o:['14 cm','21 cm','28 cm','49 cm'],a:'28 cm',e:'4 × 7 = 28 cm'},
{id:'mpa3_04',s:'maths',t:'Perimeter & Area',l:3,q:'Area of a square with 8 cm sides?',o:['32 cm²','48 cm²','64 cm²','16 cm²'],a:'64 cm²',e:'8 × 8 = 64 cm²'},
{id:'mpa3_05',s:'maths',t:'Perimeter & Area',l:3,q:'Rectangle: area 24 cm², width 4 cm. What is the length?',o:['4 cm','6 cm','8 cm','20 cm'],a:'6 cm',e:'Length = 24 ÷ 4 = 6 cm'},
{id:'mpa3_06',s:'maths',t:'Perimeter & Area',l:3,q:'Perimeter of a square with 9 cm sides?',o:['18 cm','27 cm','36 cm','81 cm'],a:'36 cm',e:'4 × 9 = 36 cm'},
// ── L3: Data & Statistics ─────────────────────────────────
{id:'mds3_01',s:'maths',t:'Data & Statistics',l:3,q:'Mean of 2, 4, 6, 8?',o:['4','5','6','20'],a:'5',e:'(2+4+6+8) ÷ 4 = 20 ÷ 4 = 5'},
{id:'mds3_02',s:'maths',t:'Data & Statistics',l:3,q:'Bar chart: Mon=5, Tue=8, Wed=3. Total?',o:['13','14','16','18'],a:'16',e:'5 + 8 + 3 = 16'},
{id:'mds3_03',s:'maths',t:'Data & Statistics',l:3,q:'Mode of 3, 5, 3, 7, 5, 3?',o:['3','5','7','4.3'],a:'3',e:'Mode = most frequent. 3 appears 3 times.'},
{id:'mds3_04',s:'maths',t:'Data & Statistics',l:3,q:'Median of 1, 3, 5, 7, 9?',o:['3','5','7','9'],a:'5',e:'Middle value of 5 numbers = 3rd = 5'},
{id:'mds3_05',s:'maths',t:'Data & Statistics',l:3,q:'Pictogram: each symbol = 4, there are 5 symbols. Total?',o:['5','9','20','25'],a:'20',e:'5 × 4 = 20'},
{id:'mds3_06',s:'maths',t:'Data & Statistics',l:3,q:'Range of 4, 7, 2, 9, 1?',o:['5','7','8','9'],a:'8',e:'Range = 9 − 1 = 8'},
// ── L3: Problem Solving ───────────────────────────────────
{id:'mps3_01',s:'maths',t:'Problem Solving',l:3,q:'Tom has £5.00, buys a pen for £1.75. Change?',o:['£2.75','£3.00','£3.25','£3.75'],a:'£3.25',e:'£5.00 − £1.75 = £3.25'},
{id:'mps3_02',s:'maths',t:'Problem Solving',l:3,q:'Box holds 6 eggs. How many boxes for 42 eggs?',o:['6','7','8','9'],a:'7',e:'42 ÷ 6 = 7'},
{id:'mps3_03',s:'maths',t:'Problem Solving',l:3,q:'24 children in 4 equal groups. How many per group?',o:['4','5','6','8'],a:'6',e:'24 ÷ 4 = 6'},
{id:'mps3_04',s:'maths',t:'Problem Solving',l:3,q:'Car travels 60 km/h for 3 hours. How far?',o:['63 km','120 km','180 km','200 km'],a:'180 km',e:'60 × 3 = 180 km'},
{id:'mps3_05',s:'maths',t:'Problem Solving',l:3,q:'Sara has 3× as many stickers as Priya. Priya has 12. Sara has…?',o:['9','24','36','48'],a:'36',e:'3 × 12 = 36'},
{id:'mps3_06',s:'maths',t:'Problem Solving',l:3,q:'Next in sequence: 4, 8, 12, 16, ___?',o:['18','19','20','24'],a:'20',e:'Adds 4 each time. 16 + 4 = 20'},
// ── L3: Vocabulary ────────────────────────────────────────
{id:'ev3_01',s:'english',t:'Vocabulary',l:3,q:'What does "enormous" mean?',o:['Tiny','Beautiful','Very large','Dangerous'],a:'Very large',e:'"Enormous" means extremely large'},
{id:'ev3_02',s:'english',t:'Vocabulary',l:3,q:'What does "ancient" mean?',o:['Modern','Very old','Broken','Hidden'],a:'Very old',e:'"Ancient" means belonging to the very distant past'},
{id:'ev3_03',s:'english',t:'Vocabulary',l:3,q:'What does "timid" mean?',o:['Brave','Clever','Shy and nervous','Loud'],a:'Shy and nervous',e:'"Timid" means lacking confidence, easily frightened'},
{id:'ev3_04',s:'english',t:'Vocabulary',l:3,q:'What does "transparent" mean?',o:['Colourful','See-through','Heavy','Invisible'],a:'See-through',e:'"Transparent" means able to be seen through'},
{id:'ev3_05',s:'english',t:'Vocabulary',l:3,q:'What does "reluctant" mean?',o:['Excited','Unhappy','Unwilling','Confused'],a:'Unwilling',e:'"Reluctant" means not wanting to do something'},
{id:'ev3_06',s:'english',t:'Vocabulary',l:3,q:'What does "summit" mean?',o:['Valley','River','Top of a mountain','Bottom'],a:'Top of a mountain',e:'"Summit" = the highest point'},
{id:'ev3_07',s:'english',t:'Vocabulary',l:3,q:'What does "villain" mean?',o:['Hero','Bad character','Side character','King'],a:'Bad character',e:'A villain is an evil or wicked character'},
{id:'ev3_08',s:'english',t:'Vocabulary',l:3,q:'What does "predict" mean?',o:['To look back','To say what will happen','To explain','To describe'],a:'To say what will happen',e:'"Predict" = say what you think will happen'},
{id:'ev3_09',s:'english',t:'Vocabulary',l:3,q:'What does "magnificent" mean?',o:['Ordinary','Very impressive','Small','Frightening'],a:'Very impressive',e:'"Magnificent" = impressively beautiful or grand'},
{id:'ev3_10',s:'english',t:'Vocabulary',l:3,q:'What does "exhausted" mean?',o:['Happy','Bored','Very tired','Angry'],a:'Very tired',e:'"Exhausted" = extremely tired'},
{id:'ev3_11',s:'english',t:'Vocabulary',l:3,q:'"The detective ___ the clues carefully." Best word?',o:['ignored','lost','examined','dropped'],a:'examined',e:'"Examined" = looked at carefully, fits a detective'},
{id:'ev3_12',s:'english',t:'Vocabulary',l:3,q:'Synonym for "happy"?',o:['Sad','Angry','Joyful','Tired'],a:'Joyful',e:'Happy = joyful (same meaning)'},
{id:'ev3_13',s:'english',t:'Vocabulary',l:3,q:'Antonym for "cold"?',o:['Warm','Icy','Freezing','Cool'],a:'Warm',e:'Cold ↔ warm are opposites'},
{id:'ev3_14',s:'english',t:'Vocabulary',l:3,q:'Synonym for "fast"?',o:['Slow','Quick','Lazy','Heavy'],a:'Quick',e:'Fast and quick both mean rapid'},
{id:'ev3_15',s:'english',t:'Vocabulary',l:3,q:'What does "cunning" mean?',o:['Clumsy','Clever at tricking','Generous','Boring'],a:'Clever at tricking',e:'"Cunning" = craftily clever'},
// ── L3: Punctuation ───────────────────────────────────────
{id:'ep3_01',s:'english',t:'Punctuation',l:3,q:'Which sentence uses a capital letter correctly?',o:['the dog barked.','The dog barked.','the Dog Barked.','THE dog barked.'],a:'The dog barked.',e:'Sentences begin with a capital letter'},
{id:'ep3_02',s:'english',t:'Punctuation',l:3,q:"Where does the apostrophe go: 'The cats toy' (one cat)?",o:["cat's toy","cats' toy","cats toy","cat toy"],a:"cat's toy",e:"One cat owns the toy: cat's (apostrophe before s)"},
{id:'ep3_03',s:'english',t:'Punctuation',l:3,q:'Correct contraction of "do not"?',o:["don't","do'nt","dont'","d'ont"],a:"don't",e:"don't: apostrophe replaces the missing 'o'"},
{id:'ep3_04',s:'english',t:'Punctuation',l:3,q:'Which sentence needs an exclamation mark?',o:['What is your name','Please sit down','Watch out','The sky is blue'],a:'Watch out',e:'"Watch out" shows urgency — needs !'},
{id:'ep3_05',s:'english',t:'Punctuation',l:3,q:'Which is punctuated correctly?',o:['I like dogs cats and rabbits.','I like dogs, cats, and rabbits.','I, like dogs cats and rabbits.','I like, dogs, cats and rabbits.'],a:'I like dogs, cats, and rabbits.',e:'Commas separate items in a list'},
{id:'ep3_06',s:'english',t:'Punctuation',l:3,q:'What punctuation ends a question?',o:['Full stop','Exclamation mark','Question mark','Comma'],a:'Question mark',e:'Questions end with ?'},
{id:'ep3_07',s:'english',t:'Punctuation',l:3,q:'"The dog wagged ___ tail." its or it\'s?',o:["it's","its","its'","it is"],a:"its",e:'"its" = possessive. "it\'s" = it is'},
{id:'ep3_08',s:'english',t:'Punctuation',l:3,q:'Where does a comma go: "After breakfast she went to school"?',o:['After "After"','After "breakfast"','After "she"','After "to"'],a:'After "breakfast"',e:'Comma after introductory clause: "After breakfast, she..."'},
{id:'ep3_09',s:'english',t:'Punctuation',l:3,q:'"The girls dresses" — two girls. Correct form?',o:["The girl's dresses","The girls' dresses","The girls dresses","The girls's dresses"],a:"The girls' dresses",e:"Multiple girls → girls' (apostrophe after s)"},
{id:'ep3_10',s:'english',t:'Punctuation',l:3,q:'What is wrong: "The cat sat on it\'s mat"?',o:["it's should be its","Wrong capital","Missing full stop","Nothing is wrong"],a:"it's should be its",e:'"its" (possessive) not "it\'s" (it is)'},
{id:'ep3_11',s:'english',t:'Punctuation',l:3,q:'Which uses speech marks correctly?',o:['"I am hungry," said Tom.','I am hungry, "said Tom."','"I am hungry" said Tom.','"I am hungry, said Tom"'],a:'"I am hungry," said Tom.',e:'Speech marks enclose spoken words; punctuation goes inside'},
{id:'ep3_12',s:'english',t:'Punctuation',l:3,q:'Which word needs a capital? "my favourite subject is science."',o:['favourite','subject','science','my'],a:'my',e:'"My" starts the sentence — needs a capital'},
{id:'ep3_13',s:'english',t:'Punctuation',l:3,q:'What does a comma do in a list?',o:['Ends the sentence','Separates items','Adds excitement','Shows ownership'],a:'Separates items',e:'Commas separate items in a list'},
{id:'ep3_14',s:'english',t:'Punctuation',l:3,q:'Correct sentence?',o:["I went to london last summer.","I went to London last summer.","i went to london last summer.","I went to london Last summer."],a:"I went to London last summer.",e:'London is a proper noun — always capitalised'},
{id:'ep3_15',s:'english',t:'Punctuation',l:3,q:'Contraction of "I am"?',o:["I'm","Im'","I'am","Iam"],a:"I'm",e:"I'm: apostrophe replaces 'a' in 'am'"},
// ── L3: Grammar ───────────────────────────────────────────
{id:'eg3_01',s:'english',t:'Grammar',l:3,q:'What is a noun?',o:['An action word','A describing word','A naming word','A joining word'],a:'A naming word',e:'A noun names a person, place, thing or idea'},
{id:'eg3_02',s:'english',t:'Grammar',l:3,q:'What is a verb?',o:['A naming word','An action word','A describing word','A connecting word'],a:'An action word',e:'A verb expresses an action or state'},
{id:'eg3_03',s:'english',t:'Grammar',l:3,q:'What is an adjective?',o:['A naming word','An action word','A word that describes a noun','A joining word'],a:'A word that describes a noun',e:'Adjectives describe nouns'},
{id:'eg3_04',s:'english',t:'Grammar',l:3,q:'Which word is an adjective in "The tall tree swayed"?',o:['The','tall','tree','swayed'],a:'tall',e:'"Tall" describes the tree = adjective'},
{id:'eg3_05',s:'english',t:'Grammar',l:3,q:'Tense of "She walked to school"?',o:['Present','Future','Past','Conditional'],a:'Past',e:'"Walked" is past tense'},
{id:'eg3_06',s:'english',t:'Grammar',l:3,q:'What is an adverb?',o:['Describes a noun','Describes a verb','Names a thing','Joins sentences'],a:'Describes a verb',e:'An adverb modifies a verb (e.g. ran quickly)'},
{id:'eg3_07',s:'english',t:'Grammar',l:3,q:'Which is a proper noun?',o:['city','school','London','teacher'],a:'London',e:'A proper noun is a specific name — always capitalised'},
{id:'eg3_08',s:'english',t:'Grammar',l:3,q:'"There are ___ biscuits left." fewer or less?',o:['fewer','less','lesser','fewest'],a:'fewer',e:'Use "fewer" for countable things'},
{id:'eg3_09',s:'english',t:'Grammar',l:3,q:'What is a conjunction?',o:['A naming word','An action word','A word that joins clauses','A describing word'],a:'A word that joins clauses',e:'Conjunctions join clauses (and, but, because)'},
{id:'eg3_10',s:'english',t:'Grammar',l:3,q:'Which sentence is present tense?',o:['She ran fast.','She will run fast.','She runs fast.','She had run fast.'],a:'She runs fast.',e:'"Runs" is present tense'},
{id:'eg3_11',s:'english',t:'Grammar',l:3,q:'Identify the adverb: "The boy shouted loudly"',o:['The','boy','shouted','loudly'],a:'loudly',e:'"Loudly" describes how = adverb'},
{id:'eg3_12',s:'english',t:'Grammar',l:3,q:'Which word is a pronoun in "She left her bag at home"?',o:['left','bag','home','She'],a:'She',e:'"She" is a pronoun replacing a person\'s name'},
// ── L3: Spelling ──────────────────────────────────────────
{id:'es3_01',s:'english',t:'Spelling',l:3,q:'Which is spelled correctly?',o:['recieve','receive','receve','receeve'],a:'receive',e:'i before e except after c → receive'},
{id:'es3_02',s:'english',t:'Spelling',l:3,q:'Which spelling is correct?',o:['necessary','nessecary','necesary','neccessary'],a:'necessary',e:'One c, two s: necessary'},
{id:'es3_03',s:'english',t:'Spelling',l:3,q:'Which is correct?',o:['beleive','believe','belive','beleeve'],a:'believe',e:'believe: never beLIEve a lie'},
{id:'es3_04',s:'english',t:'Spelling',l:3,q:'Which is spelled correctly?',o:['separate','seperate','separete','seperete'],a:'separate',e:'sep-a-rate: there\'s "a rat" in sepaRate'},
{id:'es3_05',s:'english',t:'Spelling',l:3,q:'Which is correct?',o:['wierd','wired','weird','werid'],a:'weird',e:'weird: exception to i-before-e rule'},
{id:'es3_06',s:'english',t:'Spelling',l:3,q:'Which is spelled correctly?',o:['accomodate','accommodate','acommodate','acomodate'],a:'accommodate',e:'Accommodate: double c AND double m'},
{id:'es3_07',s:'english',t:'Spelling',l:3,q:'Which is correct?',o:['occured','occurred','ocurred','occured'],a:'occurred',e:'occurred: double c and double r'},
{id:'es3_08',s:'english',t:'Spelling',l:3,q:'Which is correct?',o:['definately','definetly','definitely','definitly'],a:'definitely',e:'definitely: there is "finite" inside it'},
{id:'es3_09',s:'english',t:'Spelling',l:3,q:'Which is spelled correctly?',o:['environment','enviroment','enviornment','enviorment'],a:'environment',e:'en-vi-ron-ment'},
{id:'es3_10',s:'english',t:'Spelling',l:3,q:'Which is correct?',o:['grammer','gramar','grammar','gramer'],a:'grammar',e:'grammar ends in -ar not -er'},
// ── L3: Verbal Reasoning ──────────────────────────────────
{id:'evr3_01',s:'english',t:'Verbal Reasoning',l:3,q:'Odd one out: apple, banana, carrot, grape',o:['apple','banana','carrot','grape'],a:'carrot',e:'Apple, banana, grape are fruits. Carrot is a vegetable.'},
{id:'evr3_02',s:'english',t:'Verbal Reasoning',l:3,q:'"Dog" is to "puppy" as "cat" is to…',o:['kitten','kitty','cub','foal'],a:'kitten',e:'A puppy is a young dog; a kitten is a young cat'},
{id:'evr3_03',s:'english',t:'Verbal Reasoning',l:3,q:'Odd one out: red, blue, circle, green',o:['red','blue','circle','green'],a:'circle',e:'Red, blue, green are colours. Circle is a shape.'},
{id:'evr3_04',s:'english',t:'Verbal Reasoning',l:3,q:'"Hot" is to "cold" as "day" is to…',o:['sun','morning','night','week'],a:'night',e:'Hot/cold are opposites; day/night are opposites'},
{id:'evr3_05',s:'english',t:'Verbal Reasoning',l:3,q:'What comes next: BIG, BIGGER, ___?',o:['BIGGEST','BIGGESTEST','MORE BIG','MOST BIG'],a:'BIGGEST',e:'big → bigger → biggest (superlative)'},
{id:'evr3_06',s:'english',t:'Verbal Reasoning',l:3,q:'Word meaning both "flat" and "even"?',o:['bumpy','level','high','curved'],a:'level',e:'"Level" means both flat and even'},
{id:'evr3_07',s:'english',t:'Verbal Reasoning',l:3,q:'"Pen" is to "write" as "brush" is to…',o:['clean','paint','cut','build'],a:'paint',e:'A pen writes; a brush paints'},
{id:'evr3_08',s:'english',t:'Verbal Reasoning',l:3,q:'Odd one out: swimming, running, reading, cycling',o:['swimming','running','reading','cycling'],a:'reading',e:'Swimming, running, cycling are physical exercise. Reading is not.'},
{id:'evr3_09',s:'english',t:'Verbal Reasoning',l:3,q:'"Slow" is to "fast" as "cold" is to…',o:['icy','cool','hot','warm'],a:'hot',e:'Slow/fast are opposites; cold/hot are opposites'},
{id:'evr3_10',s:'english',t:'Verbal Reasoning',l:3,q:'What comes next: Monday, Tuesday, Wednesday, ___?',o:['Friday','Thursday','Saturday','Sunday'],a:'Thursday',e:'Mon, Tue, Wed, Thu, Fri, Sat, Sun'},
// ── L3: Synonyms & Antonyms ───────────────────────────────
{id:'esa3_01',s:'english',t:'Synonyms & Antonyms',l:3,q:'Synonym for "big"?',o:['tiny','small','large','narrow'],a:'large',e:'Big = large (same meaning)'},
{id:'esa3_02',s:'english',t:'Synonyms & Antonyms',l:3,q:'Antonym for "brave"?',o:['bold','courageous','fearless','cowardly'],a:'cowardly',e:'Brave ↔ cowardly (opposites)'},
{id:'esa3_03',s:'english',t:'Synonyms & Antonyms',l:3,q:'Synonym for "begin"?',o:['finish','end','start','stop'],a:'start',e:'Begin and start mean the same thing'},
{id:'esa3_04',s:'english',t:'Synonyms & Antonyms',l:3,q:'Antonym for "noisy"?',o:['loud','rowdy','quiet','busy'],a:'quiet',e:'Noisy ↔ quiet (opposites)'},
{id:'esa3_05',s:'english',t:'Synonyms & Antonyms',l:3,q:'Synonym for "smart"?',o:['slow','dull','clever','lazy'],a:'clever',e:'Smart and clever both mean intelligent'},
{id:'esa3_06',s:'english',t:'Synonyms & Antonyms',l:3,q:'Antonym for "ancient"?',o:['old','historic','modern','aged'],a:'modern',e:'Ancient ↔ modern (opposites)'},
{id:'esa3_07',s:'english',t:'Synonyms & Antonyms',l:3,q:'Synonym for "frightened"?',o:['happy','scared','angry','surprised'],a:'scared',e:'Frightened and scared both mean afraid'},
{id:'esa3_08',s:'english',t:'Synonyms & Antonyms',l:3,q:'Antonym for "arrive"?',o:['come','appear','enter','depart'],a:'depart',e:'Arrive ↔ depart (opposites)'},
// ── L3: Sentence Structure ────────────────────────────────
{id:'ess3_01',s:'english',t:'Sentence Structure',l:3,q:'Which is a complete sentence?',o:['Running fast.','The big dog.','The cat sat on the mat.','Because it rained.'],a:'The cat sat on the mat.',e:'A complete sentence has a subject and a verb'},
{id:'ess3_02',s:'english',t:'Sentence Structure',l:3,q:'"I like football ___ I hate rain." Which word makes it compound?',o:['because','although','but','if'],a:'but',e:'Compound sentences use coordinating conjunctions (and, but, or, so)'},
{id:'ess3_03',s:'english',t:'Sentence Structure',l:3,q:'Which is a complex sentence?',o:['The dog ran.','She sang and danced.','Although it was cold, she swam.','I ate fish.'],a:'Although it was cold, she swam.',e:'Complex = main clause + subordinate clause'},
{id:'ess3_04',s:'english',t:'Sentence Structure',l:3,q:'What type of sentence is "Please sit down"?',o:['Statement','Question','Exclamation','Command'],a:'Command',e:'Commands (imperatives) tell someone to do something'},
{id:'ess3_05',s:'english',t:'Sentence Structure',l:3,q:'What type is "The sun is shining"?',o:['Statement','Question','Command','Exclamation'],a:'Statement',e:'A statement gives information and ends with a full stop'},
{id:'ess3_06',s:'english',t:'Sentence Structure',l:3,q:'Subordinating conjunction in "She cried because she was sad"?',o:['She','cried','because','sad'],a:'because',e:'"Because" introduces the reason clause'},
// ── L3: Reading Comprehension ─────────────────────────────
{id:'erc3_01',s:'english',t:'Reading Comprehension',l:3,q:'"The old woman shuffled slowly along the icy path." What does shuffled suggest?',o:['She was in a hurry','She moved with short unsteady steps','She was dancing','She was running'],a:'She moved with short unsteady steps',e:'"Shuffle" = slow, dragging steps'},
{id:'erc3_02',s:'english',t:'Reading Comprehension',l:3,q:'"The children\'s faces fell when they saw the cancelled sign." What does this mean?',o:['Faces dropped off','They looked down','They became disappointed','They were surprised'],a:'They became disappointed',e:'"Faces fell" = idiom meaning they became disappointed'},
{id:'erc3_03',s:'english',t:'Reading Comprehension',l:3,q:'In a story, the "setting" is…',o:['What happens','Who is in it','Where and when it takes place','Why characters act as they do'],a:'Where and when it takes place',e:'Setting = the time and place of the story'},
{id:'erc3_04',s:'english',t:'Reading Comprehension',l:3,q:'"Despite the rain, Maya smiled." What does despite mean?',o:['Because of','In addition to','Even though','Thanks to'],a:'Even though',e:'"Despite" = even though / in spite of'},
{id:'erc3_05',s:'english',t:'Reading Comprehension',l:3,q:'What is "inference" in reading?',o:['Finding stated facts','Reading between the lines','Copying sentences','Summarising'],a:'Reading between the lines',e:'Inference = working out what is not directly stated'},
{id:'erc3_06',s:'english',t:'Reading Comprehension',l:3,q:'Read: The puppy wagged its tail and jumped up excitedly. How does the puppy feel?',o:['Happy','Scared','Tired','Hungry'],a:'Happy',e:'Wagging tail and jumping show excitement and happiness.'},
{id:'erc3_07',s:'english',t:'Reading Comprehension',l:3,q:'Read: The sky turned dark and thunder began to rumble. What will probably happen next?',o:['It will rain','The sun will shine','It will get hotter','Birds will sing'],a:'It will rain',e:'Dark skies and thunder signal rain is coming.'},
{id:'erc3_08',s:'english',t:'Reading Comprehension',l:3,q:'Read: She tiptoed past her parents room without making a sound. What does tiptoed suggest?',o:['She was being quiet','She was in a hurry','She was dancing','She was sleepy'],a:'She was being quiet',e:'Tiptoeing means walking softly to avoid noise.'},
{id:'erc3_09',s:'english',t:'Reading Comprehension',l:3,q:'Read: The old house creaked and groaned in the wind. What atmosphere does this create?',o:['Spooky','Cheerful','Peaceful','Exciting'],a:'Spooky',e:'Creaking and groaning create an eerie atmosphere.'},
{id:'erc3_10',s:'english',t:'Reading Comprehension',l:3,q:'Read: Tom smiled and opened the envelope carefully. What does carefully suggest?',o:['He cared about the contents','He was bored','He was angry','He was in a rush'],a:'He cared about the contents',e:'Taking care suggests the letter mattered to him.'},
{id:'ess3_07',s:'english',t:'Sentence Structure',l:3,q:'Which sentence is a question?',o:['Have you seen my bag?','I have seen your bag.','Look for your bag.','What a big bag!'],a:'Have you seen my bag?',e:'Questions end with a question mark.'},
{id:'ess3_08',s:'english',t:'Sentence Structure',l:3,q:'Choose the sentence that uses a conjunction correctly.',o:['I was tired but I kept going','I was tired but','I kept going but','But I was tired'],a:'I was tired but I kept going',e:'A conjunction joins two complete clauses.'},
{id:'ess3_09',s:'english',t:'Sentence Structure',l:3,q:'Which sentence has a subordinate clause?',o:['After the rain stopped, we played outside','We played outside','The rain stopped','We played and laughed'],a:'After the rain stopped, we played outside',e:'After the rain stopped depends on the main clause.'},
{id:'ess3_10',s:'english',t:'Sentence Structure',l:3,q:'Identify the adjective in: The tall boy ran quickly.',o:['tall','boy','ran','quickly'],a:'tall',e:'Adjectives describe nouns. Tall describes boy.'},
{id:'mds3_07',s:'maths',t:'Data & Statistics',l:3,q:'A pictogram shows 3 symbols for cats. Each symbol = 4 cats. How many cats?',o:['12','3','4','9'],a:'12',e:'Multiply 3 symbols by 4 cats each.'},
{id:'mds3_08',s:'maths',t:'Data & Statistics',l:3,q:'What is the mode of: 2, 4, 4, 5, 6, 6, 6, 8?',o:['6','4','5','8'],a:'6',e:'The mode is the number that appears most often.'},
{id:'mds3_09',s:'maths',t:'Data & Statistics',l:3,q:'5 children scored: 6, 8, 7, 9, 10. What is the mean score?',o:['8','7','9','10'],a:'8',e:'Add all scores (40) and divide by 5.'},
{id:'mds3_10',s:'maths',t:'Data & Statistics',l:3,q:'A spinner has 4 equal sections: red, blue, green, yellow. Probability of blue?',o:['1/4','1/2','1/3','1/8'],a:'1/4',e:'One blue section out of four equal sections.'},
{id:'mpa3_07',s:'maths',t:'Perimeter & Area',l:3,q:'A rectangle is 9cm long and 4cm wide. What is the perimeter?',o:['26cm','36cm','13cm','18cm'],a:'26cm',e:'Perimeter = 2 × (9 + 4) = 2 × 13 = 26cm.'},
{id:'mpa3_08',s:'maths',t:'Perimeter & Area',l:3,q:'A square has sides of 7cm. What is its area?',o:['49cm²','28cm²','14cm²','21cm²'],a:'49cm²',e:'Area = side × side = 7 × 7 = 49.'},
{id:'mpa3_09',s:'maths',t:'Perimeter & Area',l:3,q:'A room is 5m by 3m. How many 1m² tiles are needed to cover the floor?',o:['15','8','16','10'],a:'15',e:'Area = 5 × 3 = 15 square metres.'},
{id:'mpa3_10',s:'maths',t:'Perimeter & Area',l:3,q:'A triangle has a base of 6cm and height of 4cm. What is its area?',o:['12cm²','24cm²','10cm²','8cm²'],a:'12cm²',e:'Area = ½ × 6 × 4 = 12cm².'},
{id:'mps3_07',s:'maths',t:'Problem Solving',l:3,q:'A shop sells pens for 35p each. How much do 8 pens cost?',o:['£2.80','£2.40','£3.50','£2.00'],a:'£2.80',e:'35 × 8 = 280p = £2.80.'},
{id:'mps3_08',s:'maths',t:'Problem Solving',l:3,q:'A journey takes 2 hours 15 minutes. If you leave at 10:30, when do you arrive?',o:['12:45','12:30','12:15','13:00'],a:'12:45',e:'10:30 + 2h15m = 12:45.'},
{id:'mps3_09',s:'maths',t:'Problem Solving',l:3,q:'Share 36 sweets equally between 4 children. How many each?',o:['9','8','12','6'],a:'9',e:'36 ÷ 4 = 9.'},
{id:'mps3_10',s:'maths',t:'Problem Solving',l:3,q:'A bag of apples costs £1.20. How many bags can you buy with £6.00?',o:['5','4','6','3'],a:'5',e:'600 ÷ 120 = 5 bags.'},
{id:'mas4_01',s:'maths',t:'Addition & Subtraction',l:4,q:'A stadium has 45,670 seats. 38,895 are filled. How many are empty?',o:['6,775','7,225','6,875','7,775'],a:'6,775',e:'Subtract 38,895 from 45,670.'},
{id:'mas4_02',s:'maths',t:'Addition & Subtraction',l:4,q:'What is 30,000 minus the sum of 12,456 and 9,784?',o:['7,760','8,240','22,240','7,660'],a:'7,760',e:'Add the two numbers first, then subtract from 30,000.'},
{id:'mas4_03',s:'maths',t:'Addition & Subtraction',l:4,q:'5,400 minus X equals 2,750. What is X?',o:['2,650','3,650','2,750','8,150'],a:'2,650',e:'Subtract 2,750 from 5,400.'},
{id:'mas4_04',s:'maths',t:'Addition & Subtraction',l:4,q:'A diver is 12m below sea level and rises 5m. What is their new depth?',o:['-17m','-7m','7m','-5m'],a:'-7m',e:'Add 5 to -12.'},
{id:'mas4_05',s:'maths',t:'Addition & Subtraction',l:4,q:'A bank account has £450. A cheque for £525 is paid out. What is the balance?',o:['-£75','£75','-£125','£0'],a:'-£75',e:'Subtract 525 from 450 giving a negative balance.'},
{id:'mas4_06',s:'maths',t:'Addition & Subtraction',l:4,q:'Find the difference between the largest and smallest 5-digit numbers using digits 1,3,5,7,9.',o:['82,962','84,192','83,952','86,420'],a:'82,962',e:'Subtract 13,579 from 97,531.'},
{id:'mas4_07',s:'maths',t:'Addition & Subtraction',l:4,q:'A plane flies at 35,000ft, drops 12,450ft then rises 3,200ft. What is its height?',o:['25,750ft','22,550ft','25,850ft','24,350ft'],a:'25,750ft',e:'Subtract the drop then add the rise.'},
{id:'mas4_08',s:'maths',t:'Addition & Subtraction',l:4,q:'What number is 15,000 less than 1,000,000?',o:['985,000','850,000','995,000','975,000'],a:'985,000',e:'Subtract 15,000 from one million.'},
{id:'mas4_09',s:'maths',t:'Addition & Subtraction',l:4,q:'X + 14,350 = 20,000. Find X.',o:['5,650','6,650','5,750','4,650'],a:'5,650',e:'Subtract 14,350 from 20,000.'},
{id:'mas4_10',s:'maths',t:'Addition & Subtraction',l:4,q:'Three items cost £12.50, £15.75 and £4.20. Change from £40?',o:['£7.55','£8.55','£6.55','£9.45'],a:'£7.55',e:'Sum the items and subtract from 40.'},
{id:'man4_01',s:'maths',t:'Angles',l:4,q:'A triangle has angles of 45° and 75°. What is the third angle?',o:['60°','50°','70°','80°'],a:'60°',e:'Angles in a triangle sum to 180°.'},
{id:'man4_02',s:'maths',t:'Angles',l:4,q:'One angle on a straight line is 112°. What is the other angle?',o:['68°','78°','58°','180°'],a:'68°',e:'Angles on a straight line sum to 180°.'},
{id:'man4_03',s:'maths',t:'Angles',l:4,q:'An isosceles triangle has a top angle of 40°. What are the two base angles?',o:['70° each','40° each','60° each','50° each'],a:'70° each',e:'Base angles are equal. (180-40)÷2=70.'},
{id:'man4_04',s:'maths',t:'Angles',l:4,q:'A quadrilateral has angles 90°, 90° and 110°. What is the fourth angle?',o:['70°','80°','90°','100°'],a:'70°',e:'Angles in a quadrilateral sum to 360°.'},
{id:'man4_05',s:'maths',t:'Angles',l:4,q:'What is the interior angle of a regular hexagon?',o:['120°','100°','90°','135°'],a:'120°',e:'Total sum 720° divided by 6 sides.'},
{id:'man4_06',s:'maths',t:'Angles',l:4,q:'Two lines intersect. One angle is 55°. What is the vertically opposite angle?',o:['55°','125°','35°','180°'],a:'55°',e:'Vertically opposite angles are always equal.'},
{id:'man4_07',s:'maths',t:'Angles',l:4,q:'The exterior angle of a regular polygon is 40°. How many sides does it have?',o:['9','8','10','12'],a:'9',e:'360 ÷ 40 = 9.'},
{id:'man4_08',s:'maths',t:'Angles',l:4,q:'An angle is 3/5 of a right angle. How many degrees is it?',o:['54°','60°','45°','30°'],a:'54°',e:'90 × 3/5 = 54.'},
{id:'man4_09',s:'maths',t:'Angles',l:4,q:'A clock shows 3:00. What is the angle between the hands?',o:['90°','45°','180°','120°'],a:'90°',e:'The hands are 1/4 of the way around 360°.'},
{id:'man4_10',s:'maths',t:'Angles',l:4,q:'A reflex angle is between which two values?',o:['180° and 360°','90° and 180°','0° and 90°','270° and 360°'],a:'180° and 360°',e:'Reflex angles are greater than 180° but less than 360°.'},
{id:'mds4_01',s:'maths',t:'Data & Statistics',l:4,q:'Find the mean of 12, 15, 18 and 23.',o:['17','18','16','19'],a:'17',e:'Add all numbers and divide by 4.'},
{id:'mds4_02',s:'maths',t:'Data & Statistics',l:4,q:'A pie chart shows 25% of 120 people like apples. How many people is that?',o:['30','25','40','60'],a:'30',e:'25% = one quarter of 120.'},
{id:'mds4_03',s:'maths',t:'Data & Statistics',l:4,q:'What is the range of: -5, 2, 8, 14, -2?',o:['19','9','14','11'],a:'19',e:'Highest (14) minus lowest (-5) = 19.'},
{id:'mds4_04',s:'maths',t:'Data & Statistics',l:4,q:'A bag has 20 marbles, 5 are red. Probability of picking red?',o:['1/4','1/5','1/2','1/6'],a:'1/4',e:'5/20 simplifies to 1/4.'},
{id:'mds4_05',s:'maths',t:'Data & Statistics',l:4,q:'Find the median of: 3, 11, 7, 9, 5.',o:['7','11','5','9'],a:'7',e:'Order the numbers and find the middle: 3,5,7,9,11.'},
{id:'mds4_06',s:'maths',t:'Data & Statistics',l:4,q:'The mean of four numbers is 10. Three are 8, 12 and 11. Find the fourth.',o:['9','10','7','11'],a:'9',e:'Total must be 40. 40 - 8 - 12 - 11 = 9.'},
{id:'mds4_07',s:'maths',t:'Data & Statistics',l:4,q:'In a survey of 200 people, 15% said No. How many said Yes?',o:['170','30','185','150'],a:'170',e:'85% said Yes. 0.85 × 200 = 170.'},
{id:'mds4_08',s:'maths',t:'Data & Statistics',l:4,q:'What is the mode of: 4, 5, 5, 6, 7, 8, 8, 8?',o:['8','5','6','4'],a:'8',e:'The mode is the most frequent value.'},
{id:'mds4_09',s:'maths',t:'Data & Statistics',l:4,q:'A bar chart scale is 1cm = 2 children. A bar is 10cm high. How many children?',o:['20','10','40','5'],a:'20',e:'Multiply bar height by the scale factor.'},
{id:'mds4_10',s:'maths',t:'Data & Statistics',l:4,q:'A fair die is rolled. What is the probability of a prime number?',o:['1/2','1/3','2/3','1/6'],a:'1/2',e:'Primes on a die: 2, 3, 5. That is 3/6 = 1/2.'},
{id:'mdc4_01',s:'maths',t:'Decimals',l:4,q:'Multiply 3.4 by 2.5.',o:['8.5','8.4','7.5','9.5'],a:'8.5',e:'34 × 25 = 850, then place decimal point.'},
{id:'mdc4_02',s:'maths',t:'Decimals',l:4,q:'Divide 14.4 by 1.2.',o:['12','1.2','144','120'],a:'12',e:'144 ÷ 12 = 12 after moving the decimal point.'},
{id:'mdc4_03',s:'maths',t:'Decimals',l:4,q:'Order from smallest to largest: 0.304, 0.34, 0.034, 0.3.',o:['0.034, 0.3, 0.304, 0.34','0.3, 0.034, 0.304, 0.34','0.034, 0.304, 0.3, 0.34','0.34, 0.304, 0.3, 0.034'],a:'0.034, 0.3, 0.304, 0.34',e:'Compare digit by digit from tenths.'},
{id:'mdc4_04',s:'maths',t:'Decimals',l:4,q:'What is 0.625 as a fraction in its simplest form?',o:['5/8','3/4','6/10','5/6'],a:'5/8',e:'625/1000 simplifies to 5/8.'},
{id:'mdc4_05',s:'maths',t:'Decimals',l:4,q:'Subtract 4.56 from 10.',o:['5.44','6.44','5.54','4.44'],a:'5.44',e:'10.00 − 4.56 = 5.44.'},
{id:'mdc4_06',s:'maths',t:'Decimals',l:4,q:'What is 7/20 as a decimal?',o:['0.35','0.7','0.14','0.3'],a:'0.35',e:'7 ÷ 20 = 0.35.'},
{id:'mdc4_07',s:'maths',t:'Decimals',l:4,q:'A 2.5m ribbon is cut into 4 equal pieces. How long is each?',o:['0.625m','0.5m','0.75m','0.65m'],a:'0.625m',e:'2.5 ÷ 4 = 0.625.'},
{id:'mdc4_08',s:'maths',t:'Decimals',l:4,q:'Round 14.567 to two decimal places.',o:['14.57','14.56','14.60','15.00'],a:'14.57',e:'The third decimal is 7, so round up.'},
{id:'mdc4_09',s:'maths',t:'Decimals',l:4,q:'Find the value of 0.2 × 0.2 × 0.2.',o:['0.008','0.08','0.8','0.0008'],a:'0.008',e:'2×2×2=8, then move decimal 3 places.'},
{id:'mdc4_10',s:'maths',t:'Decimals',l:4,q:'Add 0.05 + 0.5 + 5.005.',o:['5.555','5.105','5.06','6.05'],a:'5.555',e:'Align decimals carefully: 0.050+0.500+5.005.'},
{id:'mgs4_01',s:'maths',t:'Geometry – Shapes',l:4,q:'How many vertices does a triangular prism have?',o:['6','5','9','4'],a:'6',e:'Two triangular faces each with 3 vertices = 6.'},
{id:'mgs4_02',s:'maths',t:'Geometry – Shapes',l:4,q:'Point A is at (-2, 3). It is reflected in the x-axis. New coordinates?',o:['(-2,-3)','(2,3)','(2,-3)','(3,-2)'],a:'(-2,-3)',e:'Reflection in x-axis flips the y-coordinate sign.'},
{id:'mgs4_03',s:'maths',t:'Geometry – Shapes',l:4,q:'A shape is translated 3 left and 4 up from (1,1). New position?',o:['(-2,5)','(4,5)','(-2,-3)','(4,-3)'],a:'(-2,5)',e:'Subtract 3 from x and add 4 to y.'},
{id:'mgs4_04',s:'maths',t:'Geometry – Shapes',l:4,q:'How many edges does a square-based pyramid have?',o:['8','5','4','12'],a:'8',e:'4 on the base plus 4 rising to the apex.'},
{id:'mgs4_05',s:'maths',t:'Geometry – Shapes',l:4,q:'What 3D shape does a net of 6 equal squares make?',o:['Cube','Cuboid','Pyramid','Prism'],a:'Cube',e:'A cube has six identical square faces.'},
{id:'mgs4_06',s:'maths',t:'Geometry – Shapes',l:4,q:'Which is a property of a rhombus?',o:['Diagonals bisect at 90°','All angles are 90°','No parallel sides','Only two equal sides'],a:'Diagonals bisect at 90°',e:'Rhombus diagonals cross at right angles.'},
{id:'mgs4_07',s:'maths',t:'Geometry – Shapes',l:4,q:'A regular octagon has how many lines of symmetry?',o:['8','4','0','16'],a:'8',e:'A regular polygon has lines of symmetry equal to its number of sides.'},
{id:'mgs4_08',s:'maths',t:'Geometry – Shapes',l:4,q:'What is the sum of interior angles in a pentagon?',o:['540°','360°','720°','180°'],a:'540°',e:'Formula: (n-2) × 180 = 3 × 180 = 540.'},
{id:'mgs4_09',s:'maths',t:'Geometry – Shapes',l:4,q:'A 3D shape has 1 curved face and 0 edges. What is it?',o:['Sphere','Cone','Cylinder','Hemisphere'],a:'Sphere',e:'A sphere is one continuous curved surface.'},
{id:'mgs4_10',s:'maths',t:'Geometry – Shapes',l:4,q:'A circle has a radius of 5cm. What is the diameter?',o:['10cm','25cm','5cm','15cm'],a:'10cm',e:'Diameter = 2 × radius.'},
{id:'mmu4_01',s:'maths',t:'Measurement & Units',l:4,q:'How many millilitres are in 2.4 litres?',o:['2,400','240','24,000','24'],a:'2,400',e:'Multiply litres by 1,000.'},
{id:'mmu4_02',s:'maths',t:'Measurement & Units',l:4,q:'Convert 5.5 kilometres to metres.',o:['5,500','550','55,000','55'],a:'5,500',e:'Multiply km by 1,000.'},
{id:'mmu4_03',s:'maths',t:'Measurement & Units',l:4,q:'A film starts at 22:45 and lasts 130 minutes. What time does it end?',o:['00:55','01:15','23:55','00:45'],a:'00:55',e:'22:45 + 2h10m = 00:55.'},
{id:'mmu4_04',s:'maths',t:'Measurement & Units',l:4,q:'How many grams are in 3.05 kilograms?',o:['3,050','3,500','305','30,500'],a:'3,050',e:'Multiply kilograms by 1,000.'},
{id:'mmu4_05',s:'maths',t:'Measurement & Units',l:4,q:'A scale shows 450g. How much more to make 1.2kg?',o:['750g','650g','850g','550g'],a:'750g',e:'1,200 − 450 = 750g.'},
{id:'mmu4_06',s:'maths',t:'Measurement & Units',l:4,q:'What is 45mm in centimetres?',o:['4.5cm','450cm','0.45cm','45cm'],a:'4.5cm',e:'Divide millimetres by 10.'},
{id:'mmu4_07',s:'maths',t:'Measurement & Units',l:4,q:'A bottle holds 75cl. How many 150ml glasses can it fill?',o:['5','2','10','4'],a:'5',e:'75cl = 750ml. 750 ÷ 150 = 5.'},
{id:'mmu4_08',s:'maths',t:'Measurement & Units',l:4,q:'How many seconds are in 12 minutes?',o:['720','600','1,200','60'],a:'720',e:'12 × 60 = 720.'},
{id:'mmu4_09',s:'maths',t:'Measurement & Units',l:4,q:'A race is 5,000m. A runner has done 3.2km. How far to go?',o:['1.8km','2.8km','1,200m','1.5km'],a:'1.8km',e:'5km − 3.2km = 1.8km.'},
{id:'mmu4_10',s:'maths',t:'Measurement & Units',l:4,q:'Which is heavier: 2,500g or 2.2kg?',o:['2,500g','2.2kg','Equal','Neither'],a:'2,500g',e:'2.2kg = 2,200g, so 2,500g is heavier.'},
{id:'mpc4_01',s:'maths',t:'Percentages',l:4,q:'Find 15% of 120.',o:['18','12','20','15'],a:'18',e:'10% = 12, 5% = 6. Total = 18.'},
{id:'mpc4_02',s:'maths',t:'Percentages',l:4,q:'A coat costs £80 and is reduced by 25%. What is the new price?',o:['£60','£20','£75','£65'],a:'£60',e:'25% of 80 = 20. 80 − 20 = 60.'},
{id:'mpc4_03',s:'maths',t:'Percentages',l:4,q:'Express 12 as a percentage of 40.',o:['30%','25%','40%','12%'],a:'30%',e:'12/40 = 3/10 = 30%.'},
{id:'mpc4_04',s:'maths',t:'Percentages',l:4,q:'A price rises from £50 to £60. What is the percentage increase?',o:['20%','10%','25%','15%'],a:'20%',e:'Increase of 10 is 1/5 of original 50.'},
{id:'mpc4_05',s:'maths',t:'Percentages',l:4,q:'What is 17.5% of 200?',o:['35','17.5','34','40'],a:'35',e:'17.5 × 2 = 35.'},
{id:'mpc4_06',s:'maths',t:'Percentages',l:4,q:'After a 10% discount an item costs £45. What was the original price?',o:['£50','£49.50','£55','£40'],a:'£50',e:'90% = £45, so 100% = £50.'},
{id:'mpc4_07',s:'maths',t:'Percentages',l:4,q:'Which is larger: 2/5 or 35%?',o:['2/5','35%','They are equal','Cannot tell'],a:'2/5',e:'2/5 = 40%, which is larger than 35%.'},
{id:'mpc4_08',s:'maths',t:'Percentages',l:4,q:'What is 120% of 50?',o:['60','70','55','120'],a:'60',e:'100% of 50 is 50, plus 20% (10) = 60.'},
{id:'mpc4_09',s:'maths',t:'Percentages',l:4,q:'In a class of 30, 60% are boys. How many girls?',o:['12','18','15','20'],a:'12',e:'40% are girls. 0.4 × 30 = 12.'},
{id:'mpc4_10',s:'maths',t:'Percentages',l:4,q:'VAT is 20%. An item costs £150 before VAT. What is the total?',o:['£180','£170','£150.20','£200'],a:'£180',e:'20% of 150 = 30. 150 + 30 = 180.'},
{id:'mpa4_01',s:'maths',t:'Perimeter & Area',l:4,q:'Area of a triangle with base 8cm and height 5cm?',o:['20cm²','40cm²','13cm²','26cm²'],a:'20cm²',e:'Area = ½ × base × height = ½ × 8 × 5.'},
{id:'mpa4_02',s:'maths',t:'Perimeter & Area',l:4,q:'Volume of a cuboid with sides 3cm, 4cm and 10cm?',o:['120cm³','17cm³','70cm³','60cm³'],a:'120cm³',e:'Volume = length × width × height.'},
{id:'mpa4_03',s:'maths',t:'Perimeter & Area',l:4,q:'A square has a perimeter of 32cm. What is its area?',o:['64cm²','32cm²','16cm²','128cm²'],a:'64cm²',e:'Side = 32 ÷ 4 = 8cm. Area = 8 × 8 = 64.'},
{id:'mpa4_04',s:'maths',t:'Perimeter & Area',l:4,q:'Area of a parallelogram with base 12cm and height 7cm?',o:['84cm²','42cm²','38cm²','96cm²'],a:'84cm²',e:'Area = base × height = 12 × 7.'},
{id:'mpa4_05',s:'maths',t:'Perimeter & Area',l:4,q:'A 4×5 rectangle is joined to a 2×2 square. What is the total area?',o:['24cm²','20cm²','22cm²','28cm²'],a:'24cm²',e:'20 + 4 = 24cm².'},
{id:'mpa4_06',s:'maths',t:'Perimeter & Area',l:4,q:'A room is 6m by 4m. Carpet costs £15 per m². Total cost?',o:['£360','£240','£150','£400'],a:'£360',e:'Area = 24m². 24 × 15 = £360.'},
{id:'mpa4_07',s:'maths',t:'Perimeter & Area',l:4,q:'Perimeter of a regular hexagon with 7cm sides?',o:['42cm','49cm','35cm','56cm'],a:'42cm',e:'6 × 7 = 42cm.'},
{id:'mpa4_08',s:'maths',t:'Perimeter & Area',l:4,q:'Volume of a tank measuring 2m × 1m × 0.5m?',o:['1m³','2m³','0.5m³','1.5m³'],a:'1m³',e:'2 × 1 × 0.5 = 1m³.'},
{id:'mpa4_09',s:'maths',t:'Perimeter & Area',l:4,q:'Area of a triangle is 30cm². Base is 10cm. Find the height.',o:['6cm','3cm','5cm','10cm'],a:'6cm',e:'30 = ½ × 10 × h. So h = 6.'},
{id:'mpa4_10',s:'maths',t:'Perimeter & Area',l:4,q:'Perimeter of a semicircle with radius 10cm (π = 3.14)?',o:['51.4cm','31.4cm','41.4cm','62.8cm'],a:'51.4cm',e:'Half circumference (31.4) + diameter (20) = 51.4.'},
{id:'mps4_01',s:'maths',t:'Problem Solving',l:4,q:'Share £45 in the ratio 2:7.',o:['£10 and £35','£15 and £30','£20 and £25','£9 and £36'],a:'£10 and £35',e:'9 parts total. One part = £5. 2×5=£10, 7×5=£35.'},
{id:'mps4_02',s:'maths',t:'Problem Solving',l:4,q:'A car travels 150 miles in 3 hours. What is its speed?',o:['50mph','45mph','60mph','30mph'],a:'50mph',e:'Speed = distance ÷ time = 150 ÷ 3.'},
{id:'mps4_03',s:'maths',t:'Problem Solving',l:4,q:'If 3n + 5 = 20, what is n?',o:['5','15','7','4'],a:'5',e:'3n = 15, so n = 5.'},
{id:'mps4_04',s:'maths',t:'Problem Solving',l:4,q:'A recipe for 4 people needs 200g flour. How much for 10 people?',o:['500g','400g','600g','450g'],a:'500g',e:'50g per person × 10 = 500g.'},
{id:'mps4_05',s:'maths',t:'Problem Solving',l:4,q:'Red and blue balls are in ratio 3:5. There are 40 balls. How many are red?',o:['15','25','12','24'],a:'15',e:'8 parts total. One part = 5. Red = 3 × 5 = 15.'},
{id:'mps4_06',s:'maths',t:'Problem Solving',l:4,q:'Two numbers sum to 25 and their difference is 7. What is the larger number?',o:['16','18','9','15'],a:'16',e:'(25 + 7) ÷ 2 = 16.'},
{id:'mps4_07',s:'maths',t:'Problem Solving',l:4,q:'A watch loses 2 minutes every hour. How much does it lose in one day?',o:['48 minutes','24 minutes','60 minutes','2 hours'],a:'48 minutes',e:'2 × 24 = 48 minutes.'},
{id:'mps4_08',s:'maths',t:'Problem Solving',l:4,q:'Train leaves at 09:15 and arrives at 11:05. How long is the journey?',o:['1h 50m','2h 10m','1h 10m','1h 55m'],a:'1h 50m',e:'Count on from 09:15 to 11:05.'},
{id:'mps4_09',s:'maths',t:'Problem Solving',l:4,q:'A book has 240 pages. I have read 3/8 of it. How many pages are left?',o:['150','90','120','180'],a:'150',e:'3/8 of 240 = 90 pages read. 240 - 90 = 150.'},
{id:'mps4_10',s:'maths',t:'Problem Solving',l:4,q:'3 apples and 2 pears cost £1.80. Pears cost 30p each. How much is one apple?',o:['40p','50p','30p','60p'],a:'40p',e:'2 pears = 60p. 180-60=120p for 3 apples. 120÷3=40p.'},
{id:'egr4_01',s:'english',t:'Grammar',l:4,q:'Identify the subordinate clause: While it was raining, we stayed inside.',o:['While it was raining','we stayed inside','raining','inside'],a:'While it was raining',e:'This clause cannot stand alone.'},
{id:'egr4_02',s:'english',t:'Grammar',l:4,q:'Which sentence is in the passive voice?',o:['The cake was eaten by the dog','The dog ate the cake','The dog is hungry','Eating cake is fun'],a:'The cake was eaten by the dog',e:'The subject receives the action in passive voice.'},
{id:'egr4_03',s:'english',t:'Grammar',l:4,q:'Choose the correct pronoun: Sarah and ___ went to the park.',o:['I','me','mine','myself'],a:'I',e:'Use subject pronoun I when it is the subject.'},
{id:'egr4_04',s:'english',t:'Grammar',l:4,q:'Identify the object: The boy kicked the ball into the net.',o:['the ball','The boy','kicked','the net'],a:'the ball',e:'The ball receives the action of the verb.'},
{id:'egr4_05',s:'english',t:'Grammar',l:4,q:'Which verb is in the past perfect tense?',o:['had seen','saw','was seeing','has seen'],a:'had seen',e:'Past perfect = had + past participle.'},
{id:'egr4_06',s:'english',t:'Grammar',l:4,q:'Identify the modal verb: You should arrive on time.',o:['should','arrive','on','time'],a:'should',e:'Modal verbs express necessity or possibility.'},
{id:'egr4_07',s:'english',t:'Grammar',l:4,q:'Find the abstract noun: The soldier showed great courage.',o:['courage','soldier','showed','great'],a:'courage',e:'Abstract nouns refer to ideas or qualities.'},
{id:'egr4_08',s:'english',t:'Grammar',l:4,q:'Which word is a relative pronoun?',o:['who','she','this','him'],a:'who',e:'Relative pronouns introduce a relative clause.'},
{id:'egr4_09',s:'english',t:'Grammar',l:4,q:'Identify the determiner: Those birds are flying south.',o:['Those','birds','flying','south'],a:'Those',e:'Determiners specify which noun is referred to.'},
{id:'egr4_10',s:'english',t:'Grammar',l:4,q:'Which sentence uses the subjunctive correctly?',o:['If I were you I would go','If I was you I would go','I wish I was taller','He suggests she goes'],a:'If I were you I would go',e:'Subjunctive uses were for hypothetical situations.'},
{id:'epu4_01',s:'english',t:'Punctuation',l:4,q:'Which sentence uses a semicolon correctly?',o:['I like tea; he likes coffee','I like tea; and coffee','I like; tea','I like tea,; he likes coffee'],a:'I like tea; he likes coffee',e:'Semicolons link two independent clauses.'},
{id:'epu4_02',s:'english',t:'Punctuation',l:4,q:'Where should the colon go? There are three colours red blue and green.',o:['After colours','After There','After three','After red'],a:'After colours',e:'A colon introduces a list after a complete clause.'},
{id:'epu4_03',s:'english',t:'Punctuation',l:4,q:'Which shows correct plural possession for boys?',o:["The boys' bags",'The boys bags','The boy bags','The boys bag'],a:"The boys' bags",e:'Apostrophe after the s for regular plurals.'},
{id:'epu4_04',s:'english',t:'Punctuation',l:4,q:'In Mr Jones, the baker, was late — what is enclosed by parenthetic commas?',o:['the baker','Mr Jones','was late','Jones'],a:'the baker',e:'Parenthetic commas enclose extra information.'},
{id:'epu4_05',s:'english',t:'Punctuation',l:4,q:'Which speech punctuation is correct?',o:['Go away! shouted Tom.','Go away! Shouted Tom.','Go away!, shouted Tom.','Go away! shouted tom.'],a:'Go away! shouted Tom.',e:'Speech tag starts lowercase; Tom is a proper noun.'},
{id:'epu4_06',s:'english',t:'Punctuation',l:4,q:'Which sentence uses its correctly?',o:['The dog wagged its tail','Its raining outside','The dog wagged it is tail','Its cold today'],a:'The dog wagged its tail',e:'Its (no apostrophe) shows possession.'},
{id:'epu4_07',s:'english',t:'Punctuation',l:4,q:'Which is punctuated correctly?',o:['Stop! he cried. We are here.','Stop, he cried, we are here.','Stop! he cried, we are here.','Stop, he cried. We are here.'],a:'Stop! he cried. We are here.',e:'Full stop ends the speech tag sentence.'},
{id:'epu4_08',s:'english',t:'Punctuation',l:4,q:'What punctuation is missing from: The childrens toys were scattered?',o:["Apostrophe in children's",'A comma','A colon','A hyphen'],a:"Apostrophe in children's",e:'Children is already plural so apostrophe before s.'},
{id:'epu4_09',s:'english',t:'Punctuation',l:4,q:'Which sentence uses a hyphen correctly?',o:['The thirty-two cats','The thirty two-cats','The-thirty two cats','The thirty two cats'],a:'The thirty-two cats',e:'Hyphens join compound numbers 21 to 99.'},
{id:'epu4_10',s:'english',t:'Punctuation',l:4,q:'Which uses brackets correctly?',o:['The sun (a star) is hot.','The sun a (star) is hot.','(The sun) a star is hot.','The sun a star (is hot).'],a:'The sun (a star) is hot.',e:'Brackets enclose parenthetical information.'},
{id:'erc4_01',s:'english',t:'Reading Comprehension',l:4,q:'Read: The ancient forest had stood for centuries, its roots tangled with secrets. What does ancient suggest?',o:['Very old','Scary','Quiet','Large'],a:'Very old',e:'Ancient means from long ago.'},
{id:'erc4_02',s:'english',t:'Reading Comprehension',l:4,q:'Read: Thunder rumbled like an angry beast, shaking the window panes. What figure of speech is used?',o:['Simile','Metaphor','Onomatopoeia','Personification'],a:'Simile',e:'Comparing using like makes it a simile.'},
{id:'erc4_03',s:'english',t:'Reading Comprehension',l:4,q:'Read: Lucy sighed, looking at the charred remains of her dinner. How does Lucy feel?',o:['Disappointed','Excited','Happy','Tired'],a:'Disappointed',e:'Charred remains suggest ruined food.'},
{id:'erc4_04',s:'english',t:'Reading Comprehension',l:4,q:'Read: The neon lights flickered, casting long eerie shadows across the alley. What is the atmosphere?',o:['Mysterious','Joyful','Bright','Ordinary'],a:'Mysterious',e:'Eerie and flickering lights create mystery.'},
{id:'erc4_05',s:'english',t:'Reading Comprehension',l:4,q:'Read: He tiptoed across the landing, careful not to wake the sleeping giant. Why did he tiptoe?',o:['To stay quiet','He was cold','He was fast','His feet hurt'],a:'To stay quiet',e:'Tiptoeing avoids making noise.'},
{id:'erc4_06',s:'english',t:'Reading Comprehension',l:4,q:'Read: The mountain peak was draped in a blanket of pristine snow. What does pristine mean?',o:['Unspoiled','Cold','Heavy','Old'],a:'Unspoiled',e:'Pristine means clean and untouched.'},
{id:'erc4_07',s:'english',t:'Reading Comprehension',l:4,q:'Read: A lone wolf howled, a mournful sound echoing through the valley. What does mournful mean?',o:['Sad','Loud','Scary','Musical'],a:'Sad',e:'Mournful expresses grief or sadness.'},
{id:'erc4_08',s:'english',t:'Reading Comprehension',l:4,q:'Read: The clock ticked relentlessly as the exam began. What does relentlessly suggest?',o:['Without stopping','Slowly','Loudly','Suddenly'],a:'Without stopping',e:'Relentlessly means in an unceasing way.'},
{id:'erc4_09',s:'english',t:'Reading Comprehension',l:4,q:'Read: Her eyes sparkled like diamonds when she saw the gift. Why did her eyes sparkle?',o:['She was happy','She was crying','The room was bright','She was tired'],a:'She was happy',e:'Sparkling eyes indicate joy or excitement.'},
{id:'erc4_10',s:'english',t:'Reading Comprehension',l:4,q:'Read: The rusty gate groaned in protest as it was forced open. What is being personified?',o:['The gate','The person','The air','The hinges'],a:'The gate',e:'Groaning in protest gives human qualities to the gate.'},
{id:'ess4_01',s:'english',t:'Sentence Structure',l:4,q:'Identify the complex sentence.',o:['I went home because I was tired','I went home and I slept','I went home','I was tired'],a:'I went home because I was tired',e:'Contains an independent and a dependent clause.'},
{id:'ess4_02',s:'english',t:'Sentence Structure',l:4,q:'Identify the fronted adverbial: Late that night, the stars came out.',o:['Late that night','the stars','came out','night'],a:'Late that night',e:'The opening phrase tells us when — it is fronted.'},
{id:'ess4_03',s:'english',t:'Sentence Structure',l:4,q:'Passive version of: The chef prepared the meal.',o:['The meal was prepared by the chef','The chef was preparing the meal','The meal is prepared','Preparing was done by the chef'],a:'The meal was prepared by the chef',e:'The object becomes the subject in passive voice.'},
{id:'ess4_04',s:'english',t:'Sentence Structure',l:4,q:'Identify the relative clause: The girl who won the race is my friend.',o:['who won the race','The girl','is my friend','the race'],a:'who won the race',e:'This clause gives more information about the girl.'},
{id:'ess4_05',s:'english',t:'Sentence Structure',l:4,q:'Which sentence has a dangling modifier?',o:['Running for the bus, my hat fell off','Running for the bus, I lost my hat','My hat fell off while I ran','I lost my hat as I ran'],a:'Running for the bus, my hat fell off',e:'The hat cannot run for the bus.'},
{id:'ess4_06',s:'english',t:'Sentence Structure',l:4,q:'What type of sentence is: Go to your room!',o:['Imperative','Declarative','Interrogative','Exclamatory'],a:'Imperative',e:'Imperative sentences give commands.'},
{id:'ess4_07',s:'english',t:'Sentence Structure',l:4,q:'Identify the prepositional phrase: The cat sat under the table.',o:['under the table','The cat','sat','table'],a:'under the table',e:'Prepositional phrase shows location.'},
{id:'ess4_08',s:'english',t:'Sentence Structure',l:4,q:'Which sentence is compound-complex?',o:['I stayed but he left because it rained','I stayed because it rained','I stayed and he left','I stayed'],a:'I stayed but he left because it rained',e:'Two independent clauses plus one dependent clause.'},
{id:'ess4_09',s:'english',t:'Sentence Structure',l:4,q:'Identify the appositive: My dog, a beagle, loves bones.',o:['a beagle','My dog','loves','bones'],a:'a beagle',e:'An appositive renames the noun beside it.'},
{id:'ess4_10',s:'english',t:'Sentence Structure',l:4,q:'Find the auxiliary verb: They are playing football.',o:['are','playing','They','football'],a:'are',e:'Auxiliary verbs help form tenses.'},
{id:'esp4_01',s:'english',t:'Spelling',l:4,q:'Which is the correct spelling?',o:['accommodate','acommodate','accommodat','acommodat'],a:'accommodate',e:'Double c and double m: ac-com-mo-date.'},
{id:'esp4_02',s:'english',t:'Spelling',l:4,q:'Identify the correctly spelled word.',o:['necessary','neccessary','necesary','neccesary'],a:'necessary',e:'One c, double s: nec-es-sa-ry.'},
{id:'esp4_03',s:'english',t:'Spelling',l:4,q:'Which word has a silent letter?',o:['knight','night','kite','light'],a:'knight',e:'The k is silent in knight.'},
{id:'esp4_04',s:'english',t:'Spelling',l:4,q:'Choose the correct spelling for a feeling of shame.',o:['embarrass','embarass','embaras','embarras'],a:'embarrass',e:'Double r and double s: em-bar-rass.'},
{id:'esp4_05',s:'english',t:'Spelling',l:4,q:'Which ending is correct: independ___?',o:['ent','ant','int','unt'],a:'ent',e:'Independent ends in -ent.'},
{id:'esp4_06',s:'english',t:'Spelling',l:4,q:'Correct spelling meaning: without doubt.',o:['definitely','definately','definitly','definatly'],a:'definitely',e:'Comes from finite: def-in-ite-ly.'},
{id:'esp4_07',s:'english',t:'Spelling',l:4,q:'Which is correct?',o:['separate','seperate','separat','separete'],a:'separate',e:'Remember: there is a rat in sep-a-rate.'},
{id:'esp4_08',s:'english',t:'Spelling',l:4,q:'Choose the correctly spelled word.',o:['occurrence','ocurrence','occurence','ocurence'],a:'occurrence',e:'Double c and double r: oc-cur-rence.'},
{id:'esp4_09',s:'english',t:'Spelling',l:4,q:'Which word is spelled correctly?',o:['queue','quene','qweue','queu'],a:'queue',e:'Queue — five letters, three silent.'},
{id:'esp4_10',s:'english',t:'Spelling',l:4,q:'What is the correct plural of cactus?',o:['cacti','cactuses','cactuss','cactis'],a:'cacti',e:'Latin plurals often end in -i.'},
{id:'esa4_01',s:'english',t:'Synonyms & Antonyms',l:4,q:'Find the synonym for melancholy.',o:['sad','happy','angry','excited'],a:'sad',e:'Melancholy means a deep pensive sadness.'},
{id:'esa4_02',s:'english',t:'Synonyms & Antonyms',l:4,q:'Find the antonym for benevolent.',o:['cruel','kind','helpful','generous'],a:'cruel',e:'Benevolent means kind; its opposite is cruel.'},
{id:'esa4_03',s:'english',t:'Synonyms & Antonyms',l:4,q:'Find the synonym for tenacious.',o:['persistent','weak','lazy','fast'],a:'persistent',e:'Tenacious means holding on firmly.'},
{id:'esa4_04',s:'english',t:'Synonyms & Antonyms',l:4,q:'Find the antonym for expand.',o:['shrink','grow','stretch','enlarge'],a:'shrink',e:'Expand means grow larger; shrink means get smaller.'},
{id:'esa4_05',s:'english',t:'Synonyms & Antonyms',l:4,q:'Synonym for precarious.',o:['unstable','safe','certain','steady'],a:'unstable',e:'Precarious means likely to fall or fail.'},
{id:'esa4_06',s:'english',t:'Synonyms & Antonyms',l:4,q:'Antonym for obscure.',o:['clear','hidden','dark','vague'],a:'clear',e:'Obscure means hard to understand; clear is the opposite.'},
{id:'esa4_07',s:'english',t:'Synonyms & Antonyms',l:4,q:'Synonym for meticulous.',o:['careful','messy','quick','careless'],a:'careful',e:'Meticulous means great attention to detail.'},
{id:'esa4_08',s:'english',t:'Synonyms & Antonyms',l:4,q:'Antonym for fragile.',o:['strong','delicate','thin','light'],a:'strong',e:'Fragile means easily broken; strong is the opposite.'},
{id:'esa4_09',s:'english',t:'Synonyms & Antonyms',l:4,q:'Synonym for candid.',o:['honest','secretive','dishonest','timid'],a:'honest',e:'Candid means truthful and straightforward.'},
{id:'esa4_10',s:'english',t:'Synonyms & Antonyms',l:4,q:'Antonym for amateur.',o:['professional','beginner','learner','novice'],a:'professional',e:'Amateur is unpaid; professional is paid and skilled.'},
{id:'evr4_01',s:'english',t:'Verbal Reasoning',l:4,q:'Complete the word SH_PE (clue: a form or outline).',o:['A','I','O','E'],a:'A',e:'The word is SHAPE.'},
{id:'evr4_02',s:'english',t:'Verbal Reasoning',l:4,q:'Find the word that does not belong: Apple, Potato, Orange, Banana.',o:['Potato','Apple','Orange','Banana'],a:'Potato',e:'Potato is a vegetable; the others are fruits.'},
{id:'evr4_03',s:'english',t:'Verbal Reasoning',l:4,q:'If A=1, B=2, C=3... what does the code 7-15-1-20 spell?',o:['GOAT','BOAT','COAT','MOAT'],a:'GOAT',e:'G=7, O=15, A=1, T=20.'},
{id:'evr4_04',s:'english',t:'Verbal Reasoning',l:4,q:'Big is to small as hot is to ___.',o:['cold','warm','fire','sun'],a:'cold',e:'These are opposite pairs.'},
{id:'evr4_05',s:'english',t:'Verbal Reasoning',l:4,q:'Find the hidden word in: He made a fast art deal.',o:['star','made','fast','deal'],a:'star',e:'fast + art contains the hidden word: st-ar.'},
{id:'evr4_06',s:'english',t:'Verbal Reasoning',l:4,q:'Which is a compound word?',o:['Football','Player','Running','Green'],a:'Football',e:'Foot + ball join to form one new word.'},
{id:'evr4_07',s:'english',t:'Verbal Reasoning',l:4,q:'Which word can follow back to make a new word?',o:['bone','side','front','top'],a:'bone',e:'Backbone is a compound word.'},
{id:'evr4_08',s:'english',t:'Verbal Reasoning',l:4,q:'Find the missing letter: PLA_E (clue: used for food).',o:['T','N','C','K'],a:'T',e:'The word is PLATE.'},
{id:'evr4_09',s:'english',t:'Verbal Reasoning',l:4,q:'Shoe is to foot as glove is to ___.',o:['hand','finger','arm','leg'],a:'hand',e:'Both items are worn on those body parts.'},
{id:'evr4_10',s:'english',t:'Verbal Reasoning',l:4,q:'Which word is an anagram of SILENT?',o:['LISTEN','TINSEL','ENLIST','INLETS'],a:'LISTEN',e:'All four are anagrams of SILENT.'},
{id:'evo4_01',s:'english',t:'Vocabulary',l:4,q:'The volcano is dormant. What does dormant mean?',o:['Inactive','Exploding','Dangerous','Extinct'],a:'Inactive',e:'Dormant means temporarily inactive or sleeping.'},
{id:'evo4_02',s:'english',t:'Vocabulary',l:4,q:'Which suffix turns act into a person who acts?',o:['or','er','ed','ing'],a:'or',e:'An actor performs actions on stage or screen.'},
{id:'evo4_03',s:'english',t:'Vocabulary',l:4,q:'What does the prefix micro- mean?',o:['Small','Large','Fast','Many'],a:'Small',e:'Micro comes from Greek meaning small.'},
{id:'evo4_04',s:'english',t:'Vocabulary',l:4,q:'Choose the most precise word: The ___ building was 100 stories tall.',o:['towering','big','high','long'],a:'towering',e:'Towering is more vivid and precise than tall.'},
{id:'evo4_05',s:'english',t:'Vocabulary',l:4,q:'Which words belong to the word family of electric?',o:['All of these','electricity only','electron only','electronic only'],a:'All of these',e:'Electricity, electron and electronic share the root.'},
{id:'evo4_06',s:'english',t:'Vocabulary',l:4,q:'What does the suffix -less mean?',o:['Without','With','Full of','More'],a:'Without',e:'-less means lacking or without something.'},
{id:'evo4_07',s:'english',t:'Vocabulary',l:4,q:'The ___ of the flowers was lovely. Choose the correct word.',o:['scent','sent','cent','send'],a:'scent',e:'Scent refers to a smell or fragrance.'},
{id:'evo4_08',s:'english',t:'Vocabulary',l:4,q:'What does verify mean?',o:['Check','Hide','Lose','Guess'],a:'Check',e:'Verify means to confirm something is true.'},
{id:'evo4_09',s:'english',t:'Vocabulary',l:4,q:'Which word describes someone very brave?',o:['valiant','timid','clever','swift'],a:'valiant',e:'Valiant means possessing or showing great courage.'},
{id:'evo4_10',s:'english',t:'Vocabulary',l:4,q:'Which prefix means against?',o:['anti-','pro-','sub-','pre-'],a:'anti-',e:'Anti- means against, as in antibiotic.'}
]; // end QUESTIONS
